// Rich per-city landing content used by the CityLanding component.
// Each entry has: hero, 4-image slider, sections (cultura, gastronomía, economía,
// gente, turismo, inversión) and headline stats. The CityLanding component falls back
// to minimal data from CITY_DETAILS + macro-region content if a key is missing here.

const CITY_LANDINGS = {
  // ═════════════════════════════ COSTA ═════════════════════════════

  tumbes: {
    nombre: 'Tumbes',
    region: 'Tumbes',
    macro: 'costa',
    hero_title: 'Tumbes · La frontera tropical del Perú',
    hero_lede: 'Donde el desierto cede al manglar y el Pacífico amanece templado todo el año. La puerta norte del país y el destino de playa más estable del Pacífico sudamericano.',
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1600&q=85',
      'https://images.unsplash.com/photo-1518709414768-a88981a4515d?w=1600&q=85',
      'https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?w=1600&q=85',
      'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=1600&q=85',
    ],
    stats: [
      { label: 'Retorno anual', value: '7.1%' },
      { label: 'Temperatura media', value: '27°C' },
      { label: 'Días de sol/año', value: '300+' },
      { label: 'A Lima en avión', value: '1h 50' },
    ],
    cultura: 'Tumbes es uno de los pocos rincones del Perú donde sobreviven los manglares costeros, declarados Santuario Nacional. La identidad tumbesina mezcla raíces tallán, herencia colonial y una vida fronteriza con Ecuador que se siente en la música, la arquitectura republicana y la celebración del Carnaval norteño.',
    gastronomia: 'La cocina tumbesina gira alrededor del mar y del manglar: conchas negras frescas con limón, arroz con cangrejo, ceviche de langostinos y sudados de pescado. Cada plato es un argumento contundente: este es el norte gastronómico que aún no ha sido descubierto por el turismo masivo.',
    economia: 'Acuicultura del langostino, pesca artesanal y un turismo de playa que crece a doble dígito anual. La proximidad con Ecuador convierte a Tumbes en plataforma logística natural para el comercio binacional.',
    gente: 'Comunidad cálida, ritmo costeño relajado y una mezcla de pescadores artesanales con familias nuevas que llegaron por las plantaciones de langostino. Pequeña pero hospitalaria — la conexión humana es inmediata.',
    turismo: 'Playas vírgenes (Punta Sal, Zorritos), Santuario Nacional Los Manglares, Reserva Nacional de Tumbes y bosques secos únicos en Sudamérica. Temporada alta perpetua: nunca llueve fuerte y el sol no falla.',
    inversion: 'Punta Sal y Zorritos viven un boom de segunda residencia: villas con vista al mar entre 220.000 y 450.000 USD que rentan a un público europeo y limeño durante todo el año. Margen de apreciación alto por escasez de oferta consolidada.',
  },

  piura: {
    nombre: 'Piura',
    region: 'Piura',
    macro: 'costa',
    hero_title: 'Piura · La ciudad del eterno calor',
    hero_lede: 'Más de 320 días de sol al año, el desierto de Sechura como horizonte y una de las cocinas más expresivas del Perú. La capital del norte que mira al Pacífico con las playas mejor conservadas del país.',
    images: [
      'https://images.unsplash.com/photo-1518709414768-a88981a4515d?w=1600&q=85',
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1600&q=85',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1600&q=85',
      'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=1600&q=85',
    ],
    stats: [
      { label: 'Retorno anual', value: '7.6%' },
      { label: 'Días de sol/año', value: '320+' },
      { label: 'Temperatura media', value: '26°C' },
      { label: 'Población metropolitana', value: '500K' },
    ],
    cultura: 'Cuna de las culturas Tallán y Vicús, Piura conserva una herencia colonial visible en sus iglesias y casonas de balcones tallados. El folclore norteño — tondero, marinera norteña, cumanana — define la identidad piurana, viva en cada peña y en el calendario de fiestas patronales.',
    gastronomia: 'Piura cocina con identidad propia: seco de chabelo, copus, majado de yuca, ceviche con limón sutil. La chicha de jora piurana es uno de los mejores fermentados del país y los algarrobos del bosque seco dan miel y harina con denominación de origen.',
    economia: 'Agroexportación (mango, banano orgánico, uva, palto), pesca artesanal e industrial, gas de Talara y un creciente sector turístico de playa. Piura es el segundo motor económico del norte después de Trujillo.',
    gente: 'El piurano es directo, alegre y orgulloso de su tierra. Las familias suelen ser amplias, las casas tienen patios y la sobremesa es ley. La integración del extranjero es inmediata: la calidez se da por sentado.',
    turismo: 'Las playas de Máncora, Vichayito, Los Órganos y Cabo Blanco son referencia nacional para surf, pesca de altura y descanso. Sechura, Catacaos (joyería en filigrana), bosque seco de Pómac, archivos arqueológicos vicús.',
    inversion: 'Máncora vive un crecimiento sostenido: villas frente al mar entre 300.000 y 800.000 USD con yields de 7-9% en alquiler vacacional. Piura ciudad ofrece oportunidades en residencial premium con apreciación anual del 5-7%.',
  },

  lambayeque: {
    nombre: 'Chiclayo',
    region: 'Lambayeque',
    macro: 'costa',
    hero_title: 'Chiclayo · La ciudad de la amistad',
    hero_lede: 'Capital del antiguo reino Mochica, hogar del Señor de Sipán y centro gastronómico imprescindible del norte. Una ciudad que combina riqueza arqueológica de talla mundial con una de las cocinas más respetadas del Perú.',
    images: [
      'https://images.unsplash.com/photo-1528072164453-f4e8ef0d475a?w=1600&q=85',
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1600&q=85',
      'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=1600&q=85',
      'https://images.unsplash.com/photo-1531065208531-4036c0dba3ca?w=1600&q=85',
    ],
    stats: [
      { label: 'Retorno anual', value: '7.2%' },
      { label: 'Sitios arqueológicos', value: '15+' },
      { label: 'Temperatura media', value: '24°C' },
      { label: 'Población metropolitana', value: '900K' },
    ],
    cultura: 'Lambayeque es la sede de tres museos arqueológicos del más alto nivel — Tumbas Reales del Señor de Sipán, Museo Brüning, Museo Sicán — que documentan dos mil años de civilización Mochica y Chimú. Túcume y Huaca Rajada son piezas clave del patrimonio precolombino del país.',
    gastronomia: 'Considerada la cocina norteña por excelencia: arroz con pato, cabrito a la chiclayana, espesado, chinguirito, king kong (postre con denominación de origen). Los mercados de Moshoqueque y Modelo son imperdibles para entender el alma culinaria peruana.',
    economia: 'Centro comercial del norte con un puerto seco que articula la sierra y la selva. Agroexportación de caña, arroz y maíz; comercio mayorista; servicios universitarios y un turismo arqueológico que crece año a año.',
    gente: 'El chiclayano se enorgullece de ser hospitalario — el lema "Ciudad de la Amistad" no es publicitario. Mezcla de raíces mochicas, descendientes españoles y migración interna del norte. Familias vivas, sobremesa larga, identidad muy marcada.',
    turismo: 'Tumbas Reales de Sipán, Huaca Rajada, Túcume, bosque de Pómac, playa Pimentel con sus tradicionales caballitos de totora, isla Lobos de Tierra. Una agenda arqueológica y natural completa.',
    inversion: 'Mercado residencial en expansión por la consolidación universitaria y comercial. Departamentos premium en zona Santa Victoria entre 90.000 y 220.000 USD. Apreciación sostenida y demanda de alquiler estudiantil estable.',
  },

  'la-libertad': {
    nombre: 'Trujillo',
    region: 'La Libertad',
    macro: 'costa',
    hero_title: 'Trujillo · La ciudad de la eterna primavera',
    hero_lede: 'Capital cultural del norte y cuna de la marinera. Ocho meses de clima perfecto, tres sitios UNESCO en su periferia y un casco histórico colonial que es uno de los mejor conservados de Sudamérica.',
    images: [
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1600&q=85',
      'https://images.unsplash.com/photo-1531065208531-4036c0dba3ca?w=1600&q=85',
      'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=1600&q=85',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1600&q=85',
    ],
    stats: [
      { label: 'Retorno anual', value: '7.4%' },
      { label: 'Sitios UNESCO', value: '2' },
      { label: 'Temperatura media', value: '21°C' },
      { label: 'Población metropolitana', value: '1.0M' },
    ],
    cultura: 'Trujillo conserva el casco histórico colonial más completo del norte peruano: 30 casonas señoriales, plaza de armas con la mayor escultura libertaria del Perú, iglesias del siglo XVII y XVIII. Es la cuna oficial de la marinera, danza nacional con su festival internacional cada enero.',
    gastronomia: 'Cuna del shámbar (sopa de los lunes), cabrito a la trujillana, sopa teóloga, frejol con seco. Los cebicheros de Huanchaco son referentes nacionales y la chicha morada artesanal trujillana es la más reconocida del Perú.',
    economia: 'Tercera economía del país por PBI. Agroindustria de espárrago, arándano y palto; minería; servicios; universidades centenarias (UNT) y un puerto activo en Salaverry. Un mercado laboral dinámico que sostiene la demanda inmobiliaria.',
    gente: 'El trujillano se siente heredero directo de la cultura mochica y chimú, y a la vez ciudadano de una ciudad universitaria moderna. Aristocrática en sus raíces y popular en sus tradiciones, la identidad trujillana es una de las más definidas del país.',
    turismo: 'Chan Chan (UNESCO) — la mayor ciudad de barro del mundo precolombino. Huacas del Sol y de la Luna, Huaca Arco Iris, balneario de Huanchaco con sus caballitos de totora milenarios. El Festival Internacional de la Marinera atrae a 100.000 personas cada enero.',
    inversion: 'El distrito de Víctor Larco (cerca de Huanchaco) y California en Trujillo viven un boom de departamentos premium entre 110.000 y 280.000 USD. Yields atractivos por demanda residencial y estudiantil consolidada.',
  },

  ancash: {
    nombre: 'Huaraz',
    region: 'Áncash',
    macro: 'costa',
    hero_title: 'Huaraz · La capital andina del trekking mundial',
    hero_lede: 'Al pie de la Cordillera Blanca — el conjunto de glaciares tropicales más alto del planeta — Huaraz es la base mundial del montañismo de altura y un destino turístico que crece sin parar.',
    images: [
      'https://images.unsplash.com/photo-1526712318848-5f38e2740d77?w=1600&q=85',
      'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1600&q=85',
      'https://images.unsplash.com/photo-1531968455001-5c5272a41129?w=1600&q=85',
      'https://images.unsplash.com/photo-1543349689-9a4d426bee8e?w=1600&q=85',
    ],
    stats: [
      { label: 'Retorno anual', value: '7.9%' },
      { label: 'Cumbres > 5.500m', value: '33' },
      { label: 'Altitud', value: '3.052 m' },
      { label: 'A Lima por carretera', value: '8h' },
    ],
    cultura: 'Áncash es uno de los corazones de la civilización Chavín — Chavín de Huántar, sitio UNESCO, fundó la cosmovisión andina hace tres mil años. La región conserva textiles vivos, festividades religiosas patronales y el quechua ancashino como lengua materna en los valles altos.',
    gastronomia: 'Cocina de altura con productos andinos puros: cuy chactado, picante de cuy, llunca, pachamanca de cordero, trucha del río Santa. Los mercados de Huaraz son el mejor escaparate para entender la despensa de la sierra norte.',
    economia: 'Minería (Antamina), agricultura andina, ganadería y turismo de aventura. Huaraz vive el ritmo del trekking internacional: temporada alta de mayo a septiembre con visitantes de Europa, EE.UU. y Asia.',
    gente: 'El huaracino combina el carácter sereno andino con una apertura hacia el viajero internacional cultivada por décadas. Comunidad de guías, cocineros y emprendedores turísticos que han aprendido a recibir al mundo sin perder identidad.',
    turismo: 'Laguna 69, Pastoruri, trekking Santa Cruz, Huascarán (6.768m), Chavín de Huántar (UNESCO), cordillera Huayhuash, baños termales de Monterrey. Es la antesala mundial al alpinismo de altura tropical.',
    inversion: 'Demanda creciente de hostales boutique, lodges y casas de campo orientadas al turismo de aventura. Casas con vista a la Cordillera Blanca entre 130.000 y 320.000 USD con yields del 7-9% en temporada alta.',
  },

  lima: {
    nombre: 'Lima',
    region: 'Lima',
    macro: 'costa',
    hero_title: 'Lima · Capital gastronómica del continente',
    hero_lede: 'Once millones de habitantes mirando al Pacífico, dos restaurantes en el top 10 mundial, ocho siglos de historia continua y la mayor concentración de capital, cultura y movimiento de toda la costa pacífica de Sudamérica.',
    images: [
      'https://images.unsplash.com/photo-1531065208531-4036c0dba3ca?w=1600&q=85',
      'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=1600&q=85',
      'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=1600&q=85',
      'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=1600&q=85',
    ],
    stats: [
      { label: 'Retorno anual', value: '7.2%' },
      { label: 'Restaurantes en World\'s 50 Best', value: '4' },
      { label: 'Población metropolitana', value: '11M' },
      { label: 'Vuelos directos a Madrid', value: '2 diarios' },
    ],
    cultura: 'Centro histórico declarado Patrimonio de la Humanidad por UNESCO en 1991: la Plaza Mayor, la Catedral, San Francisco con sus catacumbas, balcones coloniales del siglo XVII. Lima alberga el Museo Larco — la colección de arte precolombino más importante del mundo — y una escena artística contemporánea con MAC, MALI y galerías que dialogan con Buenos Aires y Ciudad de México.',
    gastronomia: 'Capital reconocida de la cocina peruana. Central (#1 World\'s 50 Best en 2023), Maido, Kjolle, Astrid&Gastón, La Mar, Isolina. Más allá de la alta cocina, Lima es picantería viva: anticuchos en Surquillo, ceviche en Chorrillos, chifa en barrio chino. Una gastronomía que el mundo viene a estudiar.',
    economia: 'Concentra el 47% del PBI peruano. Sede regional de bancos, multinacionales tecnológicas, hubs logísticos del Pacífico, industria farmacéutica y financiera. El distrito de San Isidro es el centro financiero más relevante de la costa pacífica andina.',
    gente: 'Limeño cosmopolita: sangre indígena, africana, andaluza, italiana, china, japonesa. La ciudad mira al océano y al mundo. Comunidad española consolidada (más de 30.000 residentes), escuelas internacionales, cámaras de comercio bilaterales activas.',
    turismo: 'Miraflores y Barranco como ejes del turismo internacional. Malecón de doce kilómetros sobre acantilados, parapente sobre el Pacífico, vida nocturna en Barranco bohemio, museos de talla mundial. Lima es la puerta obligatoria al Perú: 9 de cada 10 turistas extranjeros pisan la ciudad.',
    inversion: 'Miraflores, San Isidro y Barranco son los distritos premium con mayor demanda residencial extranjera. Departamentos con vista al mar desde 280.000 USD, áticos desde 700.000. Yields de 6-8% en alquiler tradicional y hasta 10% en vacacional bien gestionado.',
  },

  callao: {
    nombre: 'Callao',
    region: 'Callao',
    macro: 'costa',
    hero_title: 'Callao · El primer puerto del Pacífico sur',
    hero_lede: 'Cuatrocientos años de historia portuaria, la fortaleza colonial más imponente de Sudamérica y un proceso de regeneración urbana que está transformando barrios enteros — La Punta y Chucuito a la cabeza.',
    images: [
      'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=1600&q=85',
      'https://images.unsplash.com/photo-1531065208531-4036c0dba3ca?w=1600&q=85',
      'https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?w=1600&q=85',
      'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=1600&q=85',
    ],
    stats: [
      { label: 'Retorno anual', value: '6.6%' },
      { label: 'Población', value: '1.1M' },
      { label: 'Aeropuerto internacional', value: 'Jorge Chávez' },
      { label: 'A Miraflores', value: '20 min' },
    ],
    cultura: 'Fortaleza Real Felipe (1747), una de las construcciones militares coloniales más importantes de las Américas. Iglesia matriz, casonas republicanas en La Punta, identidad portuaria con tradición de música criolla y vals limeño que aún se canta en peñas de Bellavista.',
    gastronomia: 'Capital del ceviche limeño moderno y de la jalea: cebicherías legendarias en La Perla y el Mercado de Bellavista. La pesca diaria del Callao alimenta los mejores restaurantes de Lima.',
    economia: 'Sede del Aeropuerto Internacional Jorge Chávez (renovado 2024-2025) y del puerto principal del Perú — gateway comercial del 90% de las importaciones del país. Zona logística estratégica con plataformas industriales y residenciales en expansión.',
    gente: 'Identidad chalaca fuerte y autónoma, distinta a la limeña. Comunidad afroperuana relevante, tradición portuaria que conecta familias durante generaciones. La Punta es uno de los barrios más entrañables del país.',
    turismo: 'Real Felipe, La Punta con sus malecones, Isla San Lorenzo (excursiones), bohemia portuaria del barrio Monumental Callao convertido en distrito artístico con murales y restaurantes de autor.',
    inversion: 'La Punta y Chucuito viven una renovación silenciosa: casas frente al mar entre 180.000 y 380.000 USD con potencial fuerte de apreciación tras la apertura del nuevo aeropuerto. Mercado de oportunidad para el inversor que llega antes.',
  },

  ica: {
    nombre: 'Ica',
    region: 'Ica',
    macro: 'costa',
    hero_title: 'Ica · El oasis del desierto peruano',
    hero_lede: 'La cuna del pisco, las dunas más altas de Sudamérica, las Líneas de Nazca como UNESCO y un valle vitivinícola que está ganando reconocimiento internacional. Un destino que combina aventura, gastronomía y patrimonio.',
    images: [
      'https://images.unsplash.com/photo-1604909053522-f6bae95b1c82?w=1600&q=85',
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1600&q=85',
      'https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?w=1600&q=85',
      'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=1600&q=85',
    ],
    stats: [
      { label: 'Retorno anual', value: '8.1%' },
      { label: 'Bodegas de pisco', value: '40+' },
      { label: 'Días de sol/año', value: '340+' },
      { label: 'A Lima por carretera', value: '4h' },
    ],
    cultura: 'Cultura Paracas (700 a.C.) y cultura Nazca (200 d.C.) — dos civilizaciones que dejaron textiles, geoglifos y momias entre las mejor conservadas del mundo. Festival de la Vendimia en marzo: la fiesta del vino más importante del Perú.',
    gastronomia: 'Capital del pisco con denominación de origen. Cuarenta bodegas históricas (Tabernero, Tres Generaciones, Catador, Lovera), gastronomía del valle iqueño: cabrito, sopa seca, frejol colado, tejas y chocoteja. Maridajes pisco-cocina criolla que rivalizan con cualquier valle vitivinícola del mundo.',
    economia: 'Agroexportación líder (espárrago, uva, cítricos, palto), pisco con creciente exportación, turismo y minería. Ica es uno de los polos económicos de mayor crecimiento del país en la última década.',
    gente: 'Iqueño cálido, alegre, orgulloso de su pisco y de su tierra. Vida de valle: sobremesa, baile criollo, festividades patronales largas. Comunidad pequeña pero conectada con el comercio internacional vía agroexportación.',
    turismo: 'Líneas de Nazca (UNESCO), Huacachina (oasis natural en el desierto), Reserva Nacional de Paracas, Islas Ballestas (lobos marinos, pingüinos Humboldt), bodegas de pisco con cata. Un circuito completo en 5 días.',
    inversion: 'Casonas con bodega de pisco entre 250.000 y 600.000 USD. Inversión rural premium con yield turístico atractivo. Ica ciudad ofrece residencial creciente por la pujanza agroindustrial.',
  },

  arequipa: {
    nombre: 'Arequipa',
    region: 'Arequipa',
    macro: 'costa',
    hero_title: 'Arequipa · La Ciudad Blanca',
    hero_lede: 'Casco histórico de sillar volcánico declarado Patrimonio de la Humanidad, tres volcanes nevados como horizonte permanente y una identidad regional tan fuerte que los arequipeños se llaman a sí mismos primero arequipeños y después peruanos.',
    images: [
      'https://images.unsplash.com/photo-1543349689-9a4d426bee8e?w=1600&q=85',
      'https://images.unsplash.com/photo-1533929736458-ca588d08c8be?w=1600&q=85',
      'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=1600&q=85',
      'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=1600&q=85',
    ],
    stats: [
      { label: 'Retorno anual', value: '7.8%' },
      { label: 'Sitios UNESCO', value: '1 (centro histórico)' },
      { label: 'Altitud', value: '2.335 m' },
      { label: 'Población metropolitana', value: '1.1M' },
    ],
    cultura: 'Centro histórico construido en sillar (piedra volcánica blanca) — Plaza de Armas, Catedral, Iglesia de la Compañía, Monasterio de Santa Catalina con cuatro siglos de clausura. Cuna del escritor Mario Vargas Llosa, Premio Nobel 2010, y de una tradición intelectual que distingue a la región.',
    gastronomia: 'Reconocida por las picanterías arequipeñas — patrimonio cultural del país. Rocoto relleno, chupe de camarones, ocopa arequipeña, adobo, costillar al horno. La gastronomía arequipeña es disciplinada, técnica y con identidad propia: Lima cocina, pero Arequipa picantea.',
    economia: 'Segunda economía del Perú. Minería (Cerro Verde), agricultura altiplánica, comercio regional con Bolivia y Chile, industria textil (alpaca y vicuña), universidades centenarias y servicios financieros del sur.',
    gente: 'El arequipeño es directo, formal, orgulloso, anti-centralista. La identidad regional supera con frecuencia a la nacional: ser arequipeño es una declaración de origen. Acogida cordial al extranjero, vida cultural intensa, ritmo más pausado que Lima pero igualmente cosmopolita.',
    turismo: 'Cañón del Colca (segundo más profundo del mundo, condores al amanecer), Monasterio de Santa Catalina, Mirador de Yanahuara, ruta del sillar, valle de los Volcanes, baños termales de Chivay. Aeropuerto internacional con vuelos directos a Lima, La Paz y Santiago.',
    inversion: 'Cayma, Yanahuara y Cerro Colorado son los distritos premium. Casas con vista al Misti entre 220.000 y 550.000 USD. Yield estable del 7-8% en alquiler tradicional, mercado consolidado y con poca volatilidad.',
  },

  moquegua: {
    nombre: 'Moquegua',
    region: 'Moquegua',
    macro: 'costa',
    hero_title: 'Moquegua · El valle del pisco y el sol',
    hero_lede: 'Tradición vitivinícola colonial, viñedos a 1.400 metros, una de las mejores calidades de vida del país por nivel de ingreso y un clima soleado prácticamente todo el año.',
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1600&q=85',
      'https://images.unsplash.com/photo-1518709414768-a88981a4515d?w=1600&q=85',
      'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=1600&q=85',
      'https://images.unsplash.com/photo-1604909053522-f6bae95b1c82?w=1600&q=85',
    ],
    stats: [
      { label: 'Retorno anual', value: '7.6%' },
      { label: 'Bodegas históricas', value: '15+' },
      { label: 'Altitud', value: '1.410 m' },
      { label: 'Días de sol/año', value: '320+' },
    ],
    cultura: 'Casco colonial bien preservado, iglesias del siglo XVII, Museo Contisuyo con cinco mil años de civilización local. Tradición vitivinícola desde 1540: Moquegua produce algunos de los piscos puro Italia y mosto verde más reconocidos.',
    gastronomia: 'Cocina poco difundida pero excepcional: cacharrada, patasca moqueguana, anticucho moqueguano, ají adobado y postres con guindas y manzanas del valle. Bodegas familiares abiertas para cata y maridaje.',
    economia: 'Primera región del Perú en PBI per cápita gracias a Cuajone, Toquepala (cobre) y la planta de Ilo. La economía pública e infraestructura están entre las mejores del país.',
    gente: 'Comunidad pequeña, conservadora, hospitalaria. Familias multigeneracionales arraigadas en el valle. Identidad agrícola y minera mezcladas; vida tranquila, sin la presión urbana de Lima o Arequipa.',
    turismo: 'Ruta del pisco moqueguano, Cerro Baúl (templo Wari), petroglifos de Toro Muerto (cercanos), playas del Pacífico en Ilo a una hora. Un destino aún sin saturar.',
    inversion: 'Mercado pequeño pero estable. Casonas en valle vitivinícola entre 180.000 y 350.000 USD con potencial agroturístico. Para el inversor que busca patrimonio y exclusividad antes que volumen.',
  },

  tacna: {
    nombre: 'Tacna',
    region: 'Tacna',
    macro: 'costa',
    hero_title: 'Tacna · La ciudad heroica del sur',
    hero_lede: 'Frontera con Chile, casa de la heroica resistencia peruana de 1880, comercio binacional vibrante y uno de los climas más estables y soleados del Perú. Una ciudad sureña con identidad propia.',
    images: [
      'https://images.unsplash.com/photo-1516836018717-6dd258aebd57?w=1600&q=85',
      'https://images.unsplash.com/photo-1518709414768-a88981a4515d?w=1600&q=85',
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1600&q=85',
      'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=1600&q=85',
    ],
    stats: [
      { label: 'Retorno anual', value: '7.0%' },
      { label: 'Días de sol/año', value: '330+' },
      { label: 'Altitud', value: '562 m' },
      { label: 'Población', value: '380K' },
    ],
    cultura: 'Catedral de Tacna (con campanario de Eiffel), Plaza de Armas con la pileta ornamental y arco parabólico de los héroes. Identidad patriótica fuerte por la guerra del Pacífico y el plebiscito de 1929 que devolvió la región al Perú.',
    gastronomia: 'Cocina sureña con influencia altiplánica: picante a la tacneña, choclo con queso, chupe de camarones, soltero, ají de panca. Mistela tacneña como digestivo tradicional.',
    economia: 'Comercio fronterizo (zona franca), agricultura del valle (vid, olivos, maíz), minería y servicios. Tacna recibe a más de un millón de chilenos cada año por turismo médico y dental — un nicho económico relevante.',
    gente: 'Identidad fronteriza única: tacneño orgulloso, con conciencia histórica viva y apertura comercial al sur. Familias arraigadas, ritmo tranquilo, ciudad ordenada y limpia.',
    turismo: 'Casco histórico, paseo cívico, centros termales de Calientes, valle de Locumba con su Niño Manuelito, playas de Boca del Río. Aeropuerto con vuelos a Lima y conexión terrestre a Arica (Chile).',
    inversion: 'Mercado residencial estable con demanda binacional. Departamentos en zona céntrica entre 80.000 y 180.000 USD. Apreciación moderada pero ingresos constantes por el flujo turístico chileno.',
  },

  // ═════════════════════════════ SIERRA ═════════════════════════════

  cajamarca: {
    nombre: 'Cajamarca',
    region: 'Cajamarca',
    macro: 'sierra',
    hero_title: 'Cajamarca · Donde cayó el último Inca',
    hero_lede: 'Escenario del encuentro entre Atahualpa y Pizarro en 1532, casco colonial del siglo XVI y uno de los carnavales más auténticos del Perú. Sierra norte verde, ganadera y profundamente histórica.',
    images: [
      'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1600&q=85',
      'https://images.unsplash.com/photo-1526712318848-5f38e2740d77?w=1600&q=85',
      'https://images.unsplash.com/photo-1533929736458-ca588d08c8be?w=1600&q=85',
      'https://images.unsplash.com/photo-1547592180-85f173990554?w=1600&q=85',
    ],
    stats: [
      { label: 'Retorno anual', value: '6.8%' },
      { label: 'Altitud', value: '2.750 m' },
      { label: 'Centro histórico', value: 'Patrimonio nacional' },
      { label: 'A Lima por avión', value: '1h 20' },
    ],
    cultura: 'Cuarto del Rescate (donde Atahualpa fue retenido por Pizarro), Iglesia de Belén, Catedral, Conjunto Monumental Belén. Carnaval cajamarquino — fiesta nacional de cinco días con música, danzas yunzas y agua en las calles.',
    gastronomia: 'Lácteos premium del país: quesillos, mantequilla, manjar blanco, yogurt artesanal. Caldo verde, cuy frito con papa, humita cajamarquina, chicha de jora. La cocina lechera más rica del Perú.',
    economia: 'Minería de oro (Yanacocha), ganadería lechera y exportación, turismo histórico, agricultura andina. Universidades fuertes que sostienen la demanda urbana.',
    gente: 'Cajamarquino sereno, religioso, profundamente apegado a su tradición. Familias ganaderas de varias generaciones, comunidades campesinas con quechua activo y un casco urbano universitario joven.',
    turismo: 'Ventanillas de Otuzco, Granja Porcón, Baños del Inca, Cumbemayo (acueductos preincaicos), Kuntur Wasi, complejo arqueológico Layzón. Carnaval y Corpus Christi como ejes festivos.',
    inversion: 'Casas coloniales en centro histórico desde 90.000 USD. Mercado pequeño con apreciación lenta pero constante; oportunidad para turismo cultural y agro-residencias.',
  },

  amazonas: {
    nombre: 'Chachapoyas',
    region: 'Amazonas',
    macro: 'sierra',
    hero_title: 'Chachapoyas · El reino de las nubes',
    hero_lede: 'Capital de la cultura Chachapoya, hogar de Kuélap (la fortaleza del norte) y los sarcófagos de Karajía. Una sierra norte verde, de neblinas, valles profundos y un patrimonio aún por descubrir masivamente.',
    images: [
      'assets/ciudades-selva/amazonas.png',
      'assets/turismo-selva/amazonas.png',
      'assets/ciudades-selva/san-martin.png',
      'assets/gastronomia-selva/san-martin.png',
    ],
    stats: [
      { label: 'Retorno anual', value: '8.4%' },
      { label: 'Altitud', value: '2.334 m' },
      { label: 'Catarata Gocta', value: '771 m' },
      { label: 'A Lima por avión', value: '1h 30 (vía Jaén)' },
    ],
    cultura: 'Cultura Chachapoya — los "guerreros de las nubes" — construyó Kuélap (siglo IX), considerada el Machu Picchu del norte. Casas circulares de piedra, sarcófagos de Karajía, mausoleos de Revash. Patrimonio precolombino que recién empieza a recibir turismo masivo.',
    gastronomia: 'Cocina de altura: cuy con papas, juane regional, purtumute (frijol con maíz), chicha de jora, café orgánico chachapoyano premium con denominación de origen.',
    economia: 'Café orgánico de exportación, ganadería, turismo arqueológico en expansión tras la apertura del teleférico de Kuélap (2017). Crecimiento sostenido por inversión en infraestructura turística.',
    gente: 'Comunidades campesinas con identidad chachapoya viva, mestizaje fuerte. Hospitalidad serrana clásica, ritmo lento, conexión profunda con la tierra y la historia.',
    turismo: 'Kuélap (UNESCO en proceso), Catarata de Gocta (771m, tercera más alta del mundo), Sarcófagos de Karajía, Mausoleos de Revash, Caverna de Quiocta, Laguna de los Cóndores. Un circuito de 4-6 días.',
    inversion: 'Mercado emergente con yields altos por escasez de oferta turística consolidada. Lodges y hostales boutique entre 120.000 y 280.000 USD con potencial de apreciación fuerte.',
  },

  huanuco: {
    nombre: 'Huánuco',
    region: 'Huánuco',
    macro: 'sierra',
    hero_title: 'Huánuco · El mejor clima del mundo',
    hero_lede: 'Reconocida en su tiempo por Antonio Raimondi como "la ciudad del mejor clima del mundo": templado, soleado, sin extremos. Templo de Kotosh con 4.000 años de antigüedad y un valle agrícola exuberante.',
    images: [
      'https://images.unsplash.com/photo-1580619305218-8423a7ef79b4?w=1600&q=85',
      'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1600&q=85',
      'https://images.unsplash.com/photo-1547592180-85f173990554?w=1600&q=85',
      'https://images.unsplash.com/photo-1526712318848-5f38e2740d77?w=1600&q=85',
    ],
    stats: [
      { label: 'Retorno anual', value: '7.3%' },
      { label: 'Altitud', value: '1.912 m' },
      { label: 'Templo Kotosh', value: '4.000 años' },
      { label: 'Temperatura media', value: '20°C' },
    ],
    cultura: 'Templo de Kotosh con las "Manos Cruzadas" — una de las primeras manifestaciones escultóricas de América (2000 a.C.). Iglesia Matriz colonial, fiesta de los Negritos en diciembre — tradición patrimonial nacional.',
    gastronomia: 'Pachamanca huanuqueña, picante de cuy, locro de gallina, sancochado, chicha de jora. La región es despensa agrícola: papa, maíz, palta, frutas tropicales del bajo.',
    economia: 'Agricultura, ganadería, comercio regional, turismo cultural. Universidades públicas que dan dinamismo demográfico.',
    gente: 'Comunidad cálida y conservadora, fuerte arraigo familiar, tradición católica viva. Ritmo provinciano, calidad de vida alta por el clima y los costos.',
    turismo: 'Templo de Kotosh, Tantamayo, Tingo María (selva alta) a tres horas, Cueva de las Lechuzas, Huanchachuca. Combinación única sierra-selva accesible.',
    inversion: 'Mercado pequeño y estable, casas céntricas entre 70.000 y 180.000 USD. Oportunidad para retiro y residencia secundaria por el clima excepcional.',
  },

  pasco: {
    nombre: 'Cerro de Pasco',
    region: 'Pasco',
    macro: 'sierra',
    hero_title: 'Pasco · Altura, minería y silencio andino',
    hero_lede: 'Una de las ciudades habitadas más altas del mundo, capital minera histórica del Perú y puerta a Yanachaga-Chemillén, uno de los parques nacionales más biodiversos del país.',
    images: [
      'https://images.unsplash.com/photo-1531968455001-5c5272a41129?w=1600&q=85',
      'https://images.unsplash.com/photo-1526712318848-5f38e2740d77?w=1600&q=85',
      'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1600&q=85',
      'https://images.unsplash.com/photo-1547592180-85f173990554?w=1600&q=85',
    ],
    stats: [
      { label: 'Retorno anual', value: '6.9%' },
      { label: 'Altitud', value: '4.380 m' },
      { label: 'Reserva Junín', value: 'Ramsar' },
      { label: 'A Lima por carretera', value: '7h' },
    ],
    cultura: 'Patrimonio minero colonial, fiesta de la Virgen del Rosario, danzas autóctonas como la chonguinada y el huaylash. Identidad altiplánica fuerte, pueblos con quechua y arquitectura de adobe.',
    gastronomia: 'Cocina de puna: trucha del lago Chinchaycocha, llunca, pachamanca, asado andino. Chicha de jora artesanal en pueblos cercanos.',
    economia: 'Minería polimetálica (plomo, zinc, plata) histórica del Perú; ganadería de altura; un tímido pero creciente ecoturismo.',
    gente: 'Mineros y pastores, comunidades campesinas quechua-hablantes, hospitalaria pero discreta. La altura impone su ritmo.',
    turismo: 'Reserva Junín (laguna Chinchaycocha, ranas gigantes endémicas), Yanachaga-Chemillén (selva alta), Bosque de Rocas de Huayllay (formaciones líticas únicas).',
    inversion: 'Mercado pequeño, especializado. Más relevante para inversión rural y turismo de naturaleza que para residencia premium.',
  },

  junin: {
    nombre: 'Huancayo',
    region: 'Junín',
    macro: 'sierra',
    hero_title: 'Huancayo · Capital del Valle del Mantaro',
    hero_lede: 'El corazón comercial de la sierra central, un valle agrícola de los más fértiles del país y la cuna de la papa a la huancaína. Ciudad universitaria con dinamismo creciente y conexión rápida a Lima.',
    images: [
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1600&q=85',
      'https://images.unsplash.com/photo-1601593246562-287ed4e0ad14?w=1600&q=85',
      'https://images.unsplash.com/photo-1526712318848-5f38e2740d77?w=1600&q=85',
      'https://images.unsplash.com/photo-1547592180-85f173990554?w=1600&q=85',
    ],
    stats: [
      { label: 'Retorno anual', value: '7.5%' },
      { label: 'Altitud', value: '3.259 m' },
      { label: 'Población', value: '500K' },
      { label: 'A Lima por carretera', value: '6h (tren histórico)' },
    ],
    cultura: 'Convento de Ocopa (siglo XVIII), Catedral, Parque Identidad Huanca, Feria Dominical de Huancayo (la más antigua del país). Folclore intenso: huaylas, huayno wanca, baile de la chonguinada.',
    gastronomia: 'Pachamanca a la piedra, papa a la huancaína (origen), trucha frita, mondongo huancaíno, arroz con pato, picante de cuy. Tradición fermentada en chichas de jora premium.',
    economia: 'Centro comercial de la sierra central: agricultura del valle (papa, maíz, alcachofa), ganadería, comercio regional, universidades fuertes (UNCP). Industria láctea y textil de alpaca.',
    gente: 'Wanca alegre, trabajador, profundamente folclórico. Familias multigeneracionales en el valle, sobremesa larga, tradición del baile como articulador social.',
    turismo: 'Feria dominical, Parque Identidad Huanca, Convento de Ocopa, Cordillera Huaytapallana, Laguna Huacracocha, ruta del Mantaro con sus pueblos artesanales (Hualhuas, San Jerónimo).',
    inversion: 'Mercado en crecimiento por dinamismo universitario y comercial. Departamentos centrales entre 70.000 y 160.000 USD con yields del 7-8% por demanda estudiantil estable.',
  },

  huancavelica: {
    nombre: 'Huancavelica',
    region: 'Huancavelica',
    macro: 'sierra',
    hero_title: 'Huancavelica · El corazón profundo del Perú',
    hero_lede: 'Sierra alta auténtica, comunidades quechua-hablantes vivas, festividades religiosas y agrarias de las más auténticas del país. Una región preservada del turismo masivo, ideal para quien busca Perú profundo.',
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1600&q=85',
      'https://images.unsplash.com/photo-1526712318848-5f38e2740d77?w=1600&q=85',
      'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1600&q=85',
      'https://images.unsplash.com/photo-1547592180-85f173990554?w=1600&q=85',
    ],
    stats: [
      { label: 'Retorno anual', value: '6.4%' },
      { label: 'Altitud', value: '3.676 m' },
      { label: 'Quechua-hablantes', value: '60%+' },
      { label: 'A Lima por carretera', value: '11h' },
    ],
    cultura: 'Catedral de San Antonio, Iglesia de San Francisco, Palacio Real (de la mina de mercurio colonial). Tradiciones agrarias prehispánicas vivas: yaku raymi, herranza, pago a la tierra.',
    gastronomia: 'Pachamanca tradicional, mondongo, llunca, papas nativas en sus mil variedades, chicha de jora dulce. La cocina huancavelicana es ancestral y honesta.',
    economia: 'Agricultura andina, ganadería camélida (alpaca, llama), turismo emergente. La economía es modesta pero el costo de vida es uno de los más bajos del país.',
    gente: 'Comunidad campesina quechua viva, profundamente religiosa, anclada a la tierra. Para el visitante con interés cultural genuino, la conexión humana es excepcional.',
    turismo: 'Mina de Santa Bárbara (sitio histórico colonial), aguas termales de Sacsamarca, Templo de Uchcus Inkañan, parque arqueológico Inkawasi. Off-the-beaten-path por excelencia.',
    inversion: 'Mercado pequeño y específico. Casa colonial en centro histórico desde 50.000 USD; oportunidad de patrimonio por encima de yield.',
  },

  ayacucho: {
    nombre: 'Ayacucho',
    region: 'Ayacucho',
    macro: 'sierra',
    hero_title: 'Ayacucho · 33 iglesias y la Semana Santa más bella',
    hero_lede: 'La ciudad de las 33 iglesias coloniales, sede de la batalla que selló la independencia sudamericana en 1824 y hogar de la Semana Santa más reconocida del país, declarada Patrimonio Cultural de la Nación.',
    images: [
      'https://images.unsplash.com/photo-1533929736458-ca588d08c8be?w=1600&q=85',
      'https://images.unsplash.com/photo-1526712318848-5f38e2740d77?w=1600&q=85',
      'https://images.unsplash.com/photo-1543349689-9a4d426bee8e?w=1600&q=85',
      'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1600&q=85',
    ],
    stats: [
      { label: 'Retorno anual', value: '7.0%' },
      { label: 'Iglesias coloniales', value: '33' },
      { label: 'Altitud', value: '2.761 m' },
      { label: 'Semana Santa', value: 'Top 3 mundo' },
    ],
    cultura: 'Centro histórico colonial extraordinario, 33 iglesias entre los siglos XVI y XVIII, Pampa de la Quinua (campo de batalla de la Independencia). Capital del retablo ayacuchano y de la imaginería religiosa peruana.',
    gastronomia: 'Mondongo ayacuchano, puchero, qapchi, chicharrón, cuy chactado. Chocolate de cacao orgánico ayacuchano y pan chapla son emblemas locales.',
    economia: 'Artesanía y retablo de exportación, agricultura andina, café orgánico (provincia La Mar), turismo religioso y cultural. Universidades centenarias (UNSCH).',
    gente: 'Profundamente religioso, hospitalario, con identidad muy fuerte. Comunidad de artesanos retablistas reconocidos internacionalmente. Vida cultural intensa a pesar del tamaño medio.',
    turismo: 'Casco histórico, Semana Santa (10 días, atrae 100.000 visitantes), Pampa de Ayacucho, Wari (capital del primer imperio andino), Vilcashuamán (centro inca).',
    inversion: 'Casonas coloniales en centro histórico entre 90.000 y 220.000 USD. Mercado de patrimonio cultural con potencial alto durante temporada de Semana Santa.',
  },

  apurimac: {
    nombre: 'Abancay',
    region: 'Apurímac',
    macro: 'sierra',
    hero_title: 'Apurímac · El cañón del dios que habla',
    hero_lede: 'Cañón del Apurímac (uno de los más profundos de América), tradición arriera y rutas de trekking que conectan con Cusco. Sierra sur auténtica, aún sin saturar de turismo.',
    images: [
      'https://images.unsplash.com/photo-1526712318848-5f38e2740d77?w=1600&q=85',
      'https://images.unsplash.com/photo-1531968455001-5c5272a41129?w=1600&q=85',
      'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1600&q=85',
      'https://images.unsplash.com/photo-1547592180-85f173990554?w=1600&q=85',
    ],
    stats: [
      { label: 'Retorno anual', value: '7.2%' },
      { label: 'Altitud', value: '2.378 m' },
      { label: 'Cañón Apurímac', value: '3.000 m profundidad' },
      { label: 'A Cusco por carretera', value: '4h' },
    ],
    cultura: 'Tradición arriera y agraria, festividades patronales fuertes (Virgen del Rosario), comunidades quechua-hablantes vivas. Sondor — sitio arqueológico chanca — como referencia regional.',
    gastronomia: 'Tallarín de casa, chicharrón, picante de cuy, ponche de habas, chicha de jora. Cocina sencilla, honesta, profundamente andina.',
    economia: 'Minería (Las Bambas), agricultura, ganadería, comercio regional. Crecimiento por inversión minera; turismo cultural en desarrollo.',
    gente: 'Comunidades campesinas chankas, fuerte presencia quechua, hospitalidad clásica andina. Vida pausada, conexión con la naturaleza.',
    turismo: 'Santuario Nacional del Ampay, Cañón del Apurímac, Sondor, baños termales de Cconoc, ruta del Qhapac Ñan (camino inca a Cusco).',
    inversion: 'Mercado emergente vinculado al boom minero. Casas céntricas desde 70.000 USD con apreciación moderada.',
  },

  cusco: {
    nombre: 'Cusco',
    region: 'Cusco',
    macro: 'sierra',
    hero_title: 'Cusco · El ombligo del mundo andino',
    hero_lede: 'Capital del Imperio Inca, Patrimonio de la Humanidad desde 1983, antesala a Machu Picchu y la ciudad con mayor rentabilidad inmobiliaria del Perú. Donde la historia continua del continente americano se respira en cada calle empedrada.',
    images: [
      'https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=1600&q=85',
      'https://images.unsplash.com/photo-1580619305218-8423a7ef79b4?w=1600&q=85',
      'https://images.unsplash.com/photo-1533929736458-ca588d08c8be?w=1600&q=85',
      'https://images.unsplash.com/photo-1544025162-d76694265947?w=1600&q=85',
    ],
    stats: [
      { label: 'Retorno anual', value: '9.4%' },
      { label: 'Sitios UNESCO', value: '2' },
      { label: 'Turistas anuales', value: '3M+' },
      { label: 'Altitud', value: '3.399 m' },
    ],
    cultura: 'Plaza de Armas con Catedral del siglo XVI sobre cimientos incas, Qoricancha (Templo del Sol), Sacsayhuamán, San Blas (barrio de artesanos). El quechua se habla activamente, las festividades como el Inti Raymi y el Corpus Christi son patrimonio cultural inmaterial.',
    gastronomia: 'Cocina cusqueña reinventada en Mil (Virgilio Martínez), Cicciolina, Chicha (Gastón Acurio). Cuy al horno, chiriuchu (plato ceremonial), trucha del Urubamba, chocolate cusqueño con denominación de origen, café del Valle Sagrado.',
    economia: 'Tercera economía del Perú vía turismo (3 millones de visitantes anuales, 70% extranjeros). Sector hotelero premium, alquiler vacacional, gastronomía gourmet, artesanía textil. Mercado inmobiliario con la mayor rentabilidad del país.',
    gente: 'El cusqueño combina orgullo inca con apertura al mundo. Comunidad española consolidada (más de 5.000 residentes), nómadas digitales, expatriados europeos. Vida cultural densa, comunidad cosmopolita en barrio histórico.',
    turismo: 'Machu Picchu (700.000 visitantes/año), Valle Sagrado (Pisac, Ollantaytambo, Chinchero), Vinicunca (Montaña 7 Colores), Camino Inca, Maras-Moray, Choquequirao. Aeropuerto internacional con vuelos directos a Lima, La Paz, Bogotá.',
    inversion: 'San Blas, Centro Histórico y San Jerónimo son las zonas premium. Casas coloniales restauradas entre 280.000 y 800.000 USD. Yields del 9-11% en alquiler vacacional bien gestionado — los más altos del Perú. Apreciación anual del 5-8%.',
  },

  puno: {
    nombre: 'Puno',
    region: 'Puno',
    macro: 'sierra',
    hero_title: 'Puno · Capital folclórica del Perú',
    hero_lede: 'A orillas del Lago Titicaca — el lago navegable más alto del mundo — Puno es la capital folclórica del país, cuna de más de 300 danzas tradicionales y sede de la Fiesta de la Candelaria, Patrimonio de la Humanidad.',
    images: [
      'https://images.unsplash.com/photo-1580619305218-8423a7ef79b4?w=1600&q=85',
      'https://images.unsplash.com/photo-1526712318848-5f38e2740d77?w=1600&q=85',
      'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=1600&q=85',
      'https://images.unsplash.com/photo-1531968455001-5c5272a41129?w=1600&q=85',
    ],
    stats: [
      { label: 'Retorno anual', value: '7.4%' },
      { label: 'Lago Titicaca', value: '3.812 m' },
      { label: 'Danzas tradicionales', value: '300+' },
      { label: 'Idiomas', value: 'ES / Quechua / Aimara' },
    ],
    cultura: 'Fiesta de la Virgen de la Candelaria (febrero, UNESCO inmaterial). Cultura aimara y quechua coexistentes, islas flotantes de los Uros con totora, isla Taquile (UNESCO por su tejido). Catedral de Puno, balcón del Conde de Lemos.',
    gastronomia: 'Trucha del Titicaca, chairo, chuño, quinua, cordero al palo, sopa de quinua, pesque. Cocina altiplánica con identidad mucho más fuerte de lo que el viajero esperado anticipa.',
    economia: 'Turismo (Titicaca atrae 500.000 visitantes/año), agricultura altiplánica (quinua, papa nativa), ganadería camélida (alpaca, llama), comercio fronterizo con Bolivia. La región exporta el 60% de la quinua orgánica del Perú.',
    gente: 'Puneño con identidad aimara o quechua según el sector. Comunidad isleña en Uros y Taquile con autonomía cultural fuerte. Hospitalidad y apertura al viajero internacional cultivada por décadas.',
    turismo: 'Islas flotantes de los Uros, Taquile (UNESCO), Amantaní, Sillustani (chullpas precolombinas), Lampa, ruta a Bolivia. Tren turístico de lujo Cusco-Puno entre los más reconocidos del mundo.',
    inversion: 'Hostales y lodges con vista al lago entre 150.000 y 350.000 USD. Yield consistente por demanda turística internacional. Mercado especializado pero estable.',
  },

  // ═════════════════════════════ SELVA ═════════════════════════════

  loreto: {
    nombre: 'Iquitos',
    region: 'Loreto',
    macro: 'selva',
    hero_title: 'Iquitos · Puerto fluvial de la Amazonía',
    hero_lede: 'La ciudad más grande del mundo a la que solo se llega por avión o por río. Capital de la Amazonía peruana, hogar del mercado flotante de Belén y puerta a la mayor reserva de Amazonía inundable del planeta.',
    images: [
      'assets/ciudades-selva/loreto.png',
      'assets/turismo-selva/loreto.png',
      'assets/gastronomia-selva/loreto.png',
      'assets/ciudades-selva/ucayali.png',
    ],
    stats: [
      { label: 'Retorno anual', value: '9.2%' },
      { label: 'Solo accesible por', value: 'Río o avión' },
      { label: 'Reserva Pacaya-Samiria', value: '20.800 km²' },
      { label: 'Población', value: '470K' },
    ],
    cultura: 'Casa de Fitzcarraldo, Casa de Hierro (diseñada por Eiffel), barrio de Belén (la "Venecia amazónica"), pueblos originarios Kukama, Bora, Yagua. Tradición chamánica del ayahuasca, arte Shipibo-Conibo con su patrón kené reconocido internacionalmente.',
    gastronomia: 'Cocina amazónica icónica: paiche a la parrilla, juane, tacacho con cecina, patarashca, inchicapi, sopa motelo. Frutas exóticas: aguaje, cocona, camu camu (10x más vitamina C que la naranja). Aguajina y masato como bebidas tradicionales.',
    economia: 'Turismo amazónico (cruceros de lujo por el Amazonas), pesca, comercio fluvial, petróleo y agricultura tropical. Iquitos es la puerta económica de la Amazonía peruana hacia Brasil y Colombia.',
    gente: 'Comunidad mestiza con fuerte componente amazónico, ribereños conectados al ritmo del río. Acogimiento cálido, ritmo más lento, comunidades originarias activas culturalmente.',
    turismo: 'Reserva Nacional Pacaya-Samiria (20.800 km²), Mercado de Belén, casas flotantes, Quistococha, Lago Yarinacocha. Cruceros Aria Amazon y Delfin para safaris fluviales premium.',
    inversion: 'Casas amazónicas con vista al río entre 150.000 y 380.000 USD. Yields atractivos del 8-10% por turismo de lujo creciente. Mercado especializado pero con barreras de entrada que protegen a los pioneros.',
  },

  'san-martin': {
    nombre: 'Moyobamba',
    region: 'San Martín',
    macro: 'selva',
    hero_title: 'Moyobamba · La ciudad de las orquídeas',
    hero_lede: 'Capital de la selva alta peruana, hogar de 2.500 especies de orquídeas y de uno de los climas más equilibrados del Perú. Acceso por carretera, cataratas, aguas termales y un café orgánico premiado internacionalmente.',
    images: [
      'assets/ciudades-selva/san-martin.png',
      'assets/gastronomia-selva/san-martin.png',
      'assets/ciudades-selva/loreto.png',
      'assets/turismo-selva/loreto.png',
    ],
    stats: [
      { label: 'Retorno anual', value: '8.0%' },
      { label: 'Orquídeas', value: '2.500 especies' },
      { label: 'Altitud', value: '860 m' },
      { label: 'Café orgánico', value: 'Top 3 nacional' },
    ],
    cultura: 'Festival de la Orquídea (octubre), San Juan (junio) — fiesta amazónica nacional. Tradición de pueblos originarios Aguaruna y Awajún en provincias. Casa Bolaños, mirador del Tahuishco.',
    gastronomia: 'Juane regional, tacacho con cecina, chonta, asado de paiche, café orgánico de altura. Frutas tropicales y miel de abeja amazónica.',
    economia: 'Café orgánico de exportación (Alto Mayo), cacao, palma aceitera, ecoturismo. La región tiene el mejor café orgánico premiado del Perú.',
    gente: 'Comunidad acogedora, ritmo de selva alta, mezcla de migración serrana y población amazónica originaria. Vida tranquila, contacto natural con la biodiversidad.',
    turismo: 'Aguas termales de San Mateo, cataratas Gera y Lahuarpia, Cocha Yarinacocha, Alto Mayo (santuario nacional), Tarapoto cercana (cataratas Ahuashiyacu).',
    inversion: 'Casas con jardín tropical entre 100.000 y 240.000 USD. Demanda creciente por nómadas digitales y retiro tropical. Yield estable y costo de vida bajo.',
  },

  ucayali: {
    nombre: 'Pucallpa',
    region: 'Ucayali',
    macro: 'selva',
    hero_title: 'Pucallpa · Puerto del río Ucayali',
    hero_lede: 'Capital comercial de la selva central peruana, principal centro del arte Shipibo-Conibo y puerta a una Amazonía menos turística que Iquitos pero igual de valiosa.',
    images: [
      'assets/ciudades-selva/ucayali.png',
      'assets/ciudades-selva/loreto.png',
      'assets/ciudades-selva/madre-de-dios.png',
      'assets/gastronomia-selva/loreto.png',
    ],
    stats: [
      { label: 'Retorno anual', value: '8.6%' },
      { label: 'Río Ucayali', value: 'Tributario Amazonas' },
      { label: 'Comunidades Shipibo', value: '300+' },
      { label: 'A Lima por avión', value: '1h' },
    ],
    cultura: 'Comunidades Shipibo-Conibo y su arte kené (patrones geométricos visionarios), tradición chamánica del ayahuasca, Santa Clara, Pucallpillo. Centros de medicina tradicional reconocidos internacionalmente.',
    gastronomia: 'Cocina shipibo-mestiza: tacacho, juane, patarashca de paiche, asado de doncella, masato, aguajina, sopa motelo. Frutas amazónicas como camu camu y aguaje en abundancia.',
    economia: 'Madera, agricultura tropical, comercio fluvial con Iquitos y Brasil, turismo chamánico y de naturaleza. Crecimiento sostenido por la mejora de carreteras.',
    gente: 'Comunidad mestiza fuerte, presencia shipibo activa en distritos cercanos, hospitalidad amazónica. Para el visitante con interés cultural genuino, la conexión es muy directa.',
    turismo: 'Lago Yarinacocha, comunidades Shipibo de San Francisco y Santa Clara, Parque Natural de Pucallpa, Cataratas de Velo de Novia, retiros chamánicos.',
    inversion: 'Casas tropicales y lodges entre 90.000 y 220.000 USD. Yield atractivo y mercado emergente por desarrollo turístico cultural.',
  },

  'madre-de-dios': {
    nombre: 'Puerto Maldonado',
    region: 'Madre de Dios',
    macro: 'selva',
    hero_title: 'Puerto Maldonado · La capital de la biodiversidad',
    hero_lede: 'Frontera con Bolivia y Brasil, puerta a Tambopata y al Manu — los dos parques con la mayor concentración de biodiversidad por metro cuadrado del planeta. Eco-turismo de talla mundial y un mercado inmobiliario emergente.',
    images: [
      'assets/ciudades-selva/madre-de-dios.png',
      'assets/gastronomia-selva/madre-de-dios.png',
      'assets/ciudades-selva/loreto.png',
      'assets/turismo-selva/loreto.png',
    ],
    stats: [
      { label: 'Retorno anual', value: '8.8%' },
      { label: 'Especies de aves', value: '1.000+' },
      { label: 'Parque del Manu', value: 'UNESCO' },
      { label: 'A Cusco por avión', value: '40 min' },
    ],
    cultura: 'Pueblos originarios Ese Eja, Harakmbut, Yine. Festival de la Castaña, ritos chamánicos amazónicos, tradición de extractivismo de castaña y caucho histórico. Casa Histórica del barón del caucho Fitzcarrald.',
    gastronomia: 'Asado de paiche, juane, tacacho, sopa de motelo, parrillada amazónica, chonta. Frutas endémicas (copoazú, aguaje, camu camu). Castaña amazónica de exportación premium.',
    economia: 'Castaña, ecoturismo de lujo (lodges Tambopata e Inkaterra), agricultura tropical, oro (con problemas de extracción ilegal). El eco-turismo crece a doble dígito anual.',
    gente: 'Mezcla intensa: comunidades originarias, migración andina, brasileños y bolivianos del otro lado de la frontera. Comunidad pequeña pero internacional por el flujo turístico.',
    turismo: 'Reserva Nacional Tambopata, Parque del Manu (UNESCO), Lago Sandoval, collpa de guacamayos, Lago Valencia. Lodges premium para safaris amazónicos: Inkaterra, Tambopata Research Center, Refugio Amazonas.',
    inversion: 'Lodges y casas amazónicas entre 130.000 y 320.000 USD. Yield del 8-10% en eco-turismo de lujo. Mercado emergente con barreras de entrada que protegen al inversor pionero.',
  },
};

window.CITY_LANDINGS = CITY_LANDINGS;
