// General content per macro-region (Costa / Sierra / Selva) — meant to inspire
// the user to click into a specific city card. City-exclusive content lives in
// the per-city pages (to be built).
const MACRO_REGION_DATA = {
  costa: {
    nombre: 'Costa',
    color: '#6FA8C9',
    quechua_num: 'ꟼ Huk',
    quechua_gast: 'ꟼ Iskay · Mikhuna',
    quechua_viv: 'ꟼ Kimsa · Qucha Kawsay',
    hook_title: 'Desde los manglares hasta el desierto del sur',
    hook_lede: 'Dos mil kilómetros de Pacífico, once ciudades costeras, la cocina más reconocida del mundo y el clima más templado de Sudamérica.',
    intro: {
      eyebrow: 'ꟼ Por qué la Costa',
      titular: 'Más que un destino: una *decisión inteligente*.',
      parrafo: 'La costa peruana no es una línea entre dos tierras. Es una civilización propia. Aquí nacieron las culturas Moche, Chimú, Paracas y Nazca hace tres mil años, tejiendo textiles que hoy siguen siendo inigualables y levantando templos que aún desafían al tiempo.',
      cierre: 'Vivir aquí es despertar con el olor del mar, comer un ceviche al mediodía y brindar con pisco viendo el sol caer sobre el Pacífico. Un lujo que ya no existe en Europa.',
      pilares: ['3000 años de cultura', 'Capital gastronómica', '300 días de sol', '12h directo a Madrid'],
    },
    intro_slides: [
      { label: 'Danzas',      caption: 'Marinera norteña · baile nacional',           img: 'assets/intro-costa/danzas.png' },
      { label: 'Cultura',     caption: 'Mercado andino · textiles y tradición viva',  img: 'assets/intro-costa/cultura.png' },
      { label: 'Clima',       caption: 'Malecón de Miraflores · Pacífico templado',   img: 'assets/intro-costa/clima.jpg' },
      { label: 'Gastronomía', caption: 'Ceviche del día · limón, ají limo, cebolla',  img: 'assets/intro-costa/gastronomia.png' },
    ],
    cultura: {
      patrimonio: ['Caral · ciudad más antigua de América (UNESCO)', 'Líneas de Nazca (UNESCO)', 'Chan Chan (UNESCO)', 'Centro histórico de Lima (UNESCO)', 'Señor de Sipán'],
      festividades: ['Señor de los Milagros · octubre', 'Fiesta de la Vendimia · marzo', 'Aniversario de Lima · enero', 'Semana jubilar de Trujillo'],
      idiomas: ['Español', 'Quechua (minoritario)'],
      artesania: ['Platería limeña', 'Cerámica Chancay', 'Textil Paracas', 'Joyería Chimú'],
    },
    turismo: [
      { nombre: 'Manglares de Tumbes',                cityId: 'tumbes',      tipo: 'Natural',       desc: 'El único santuario de manglares costeros del Perú. Bosque inundado, fauna endémica y aves migratorias.', tiempo: '3 — 5 días', img: 'assets/turismo-costa/tumbes.png' },
      { nombre: 'Máncora & Cabo Blanco · Piura',      cityId: 'piura',       tipo: 'Playa',         desc: 'Capital del surf peruano, oleaje constante, pesca de altura y vida bohemia al borde del Pacífico.',      tiempo: '5 — 7 días', img: 'assets/turismo-costa/piura.png' },
      { nombre: 'Tumbas Reales de Sipán · Chiclayo',  cityId: 'lambayeque',  tipo: 'Arqueológico',  desc: 'El descubrimiento arqueológico más importante de América Latina. Tesoro mochica intacto en su museo monumental.', tiempo: '2 — 3 días', img: 'assets/turismo-costa/lambayeque.png' },
      { nombre: 'Chan Chan · Trujillo',               cityId: 'la-libertad', tipo: 'Arqueológico',  desc: 'Mayor ciudad de barro del mundo precolombino, construida por los Chimú. Patrimonio UNESCO con relieves intactos.', tiempo: '2 — 3 días', img: 'assets/turismo-costa/la-libertad.png' },
      { nombre: 'Costa Verde & Malecón · Lima',       cityId: 'lima',        tipo: 'Urbano',        desc: 'Doce kilómetros de acantilados sobre el Pacífico, playas, parapente y atardeceres dorados. El balcón natural de Lima.', tiempo: '3 — 5 días', img: 'assets/turismo-costa/lima-costa.png' },
      { nombre: 'Caral · Ciudad sagrada',             cityId: 'lima',        tipo: 'Arqueológico',  desc: 'La ciudad más antigua de América (3.000 a.C.). Patrimonio UNESCO en el valle de Supe, a 3 horas de Lima.',          tiempo: '1 — 2 días', img: 'assets/turismo-costa/lima.png' },
      { nombre: 'Real Felipe & La Punta · Callao',    cityId: 'callao',      tipo: 'Cultural',      desc: 'La fortaleza colonial más imponente de Sudamérica (1747) y el barrio portuario en plena renovación.',                tiempo: '1 — 2 días', img: 'assets/turismo-costa/callao.jpg' },
      { nombre: 'Huacachina · Oasis del desierto',    cityId: 'ica',         tipo: 'Aventura',      desc: 'Único oasis natural del Perú, rodeado de dunas. Sandboarding, tubulares y atardeceres en el desierto iqueño.',       tiempo: '2 — 3 días', img: 'assets/turismo-costa/ica.png' },
      { nombre: 'Cerro Baúl · Moquegua',              cityId: 'moquegua',    tipo: 'Cultural',      desc: 'Mesa Wari del siglo VI sobre el valle moqueguano. Templo, viñedos y rutas vitivinícolas a sus pies.',              tiempo: '2 días',     img: 'assets/turismo-costa/moquegua.png' },
      { nombre: 'Arco Parabólico · Tacna',            cityId: 'tacna',       tipo: 'Cultural',      desc: 'Monumento heroico al lado de la Catedral, símbolo del retorno de Tacna al Perú. Casco histórico vibrante.',         tiempo: '1 — 2 días', img: 'assets/turismo-costa/tacna.png' },
    ],
    gastronomia: [
      { nombre: 'Ceviche tumbesino',        cityId: 'tumbes',      desc: 'Pescado del día del litoral norteño con limón sutil, ají limo, choclo, camote y cancha tostada.',  donde: 'Tumbes',          img: 'assets/gastronomia-costa/tumbes.png' },
      { nombre: 'Cabrito norteño',          cityId: 'piura',       desc: 'Cabrito tierno macerado en chicha de jora, acompañado de arroz blanco y frijoles canarios.',         donde: 'Piura',           img: 'assets/gastronomia-costa/piura.png' },
      { nombre: 'Arroz con pato',           cityId: 'lambayeque',  desc: 'Arroz teñido con culantro y chicha de jora, pato deshilachado en su salsa de ají amarillo.',          donde: 'Chiclayo',        img: 'assets/gastronomia-costa/lambayeque.png' },
      { nombre: 'Shámbar trujillano',       cityId: 'la-libertad', desc: 'Sopa contundente de los lunes: trigo, garbanzos, frijoles, jamón ahumado y cerdo. Plato emblema norteño.', donde: 'Trujillo',    img: 'assets/gastronomia-costa/la-libertad.png' },
      { nombre: 'Causa limeña',             cityId: 'lima',        desc: 'Papa amarilla prensada con ají, cebolla y relleno de pollo, atún o cangrejo fresco.',                 donde: 'Lima',            img: 'assets/gastronomia-costa/lima.png' },
      { nombre: 'Conchitas a la chalaca',   cityId: 'callao',      desc: 'Conchas frescas del Callao en su valva con cebolla, tomate, choclo y ají limo. Tradición portuaria.',  donde: 'Callao',          img: 'assets/gastronomia-costa/callao.png' },
      { nombre: 'Carapulcra con sopa seca', cityId: 'ica',         desc: 'Papa seca con carne y maní, acompañada de fideos verdes con albahaca. Maridaje clásico iqueño.',       donde: 'Ica',             img: 'assets/gastronomia-costa/ica.png' },
      { nombre: 'Moqueguano de Camarones',  cityId: 'moquegua',    desc: 'Camarones del río Moquegua en caldo cremoso con ají amarillo, papa, queso fresco y huevo escalfado.',  donde: 'Moquegua',        img: 'assets/gastronomia-costa/moquegua.png' },
      { nombre: 'Picante a la tacneña',     cityId: 'tacna',       desc: 'Carne, mondongo y patitas en salsa de ají rojo con choclo y papa amarilla. Se acompaña con pan.',      donde: 'Tacna',           img: 'assets/gastronomia-costa/tacna.png' },
    ],
    beneficios: [
      { icon: 'sun',    titulo: 'Clima templado todo el año', desc: 'Entre 16° y 28°C del norte al sur. Sin frío europeo, sin calor extremo. 300+ días de sol.' },
      { icon: 'plane',  titulo: 'Hub aéreo directo a Europa', desc: 'Aeropuerto Jorge Chávez: vuelo directo a Madrid 12h. Conexión a toda América.' },
      { icon: 'med',    titulo: 'Red hospitalaria de primer nivel', desc: 'Clínicas Anglo Americana, Delgado, San Felipe. Cobertura con seguros internacionales.' },
      { icon: 'wifi',   titulo: 'Fibra óptica 500 Mb',         desc: 'Infraestructura top del continente. Hubs tecnológicos en Lima y Arequipa.' },
      { icon: 'euro',   titulo: 'Coste de vida 42% menor',     desc: 'Sueldo madrileño rinde como 4.830€. Restaurantes Michelin a un tercio del precio.' },
      { icon: 'edu',    titulo: 'Colegios europeos',            desc: 'Alexander von Humboldt, Franco Peruano, San Silvestre. Universidades privadas top.' },
      { icon: 'heart',  titulo: '30.000 españoles en la costa', desc: 'Instituto Cervantes, Cámara España-Perú, comunidad consolidada.' },
      { icon: 'shield', titulo: 'Distritos premium seguros',    desc: 'Miraflores, San Isidro, Yanahuara con seguridad 24/7 y patrullaje municipal.' },
    ],
    quotes: {
      cultura: {
        lead: 'Donde hay *cultura*, hay movimiento. Y donde hay *movimiento*, hay oportunidad.',
        body: 'La costa peruana reúne patrimonio, gastronomía y vida cultural activa que generan una demanda constante, tanto turística como residencial.',
        cierre: 'Invertir aquí no es solo una decisión inmobiliaria. Es entender *hacia dónde se mueve el valor*.',
      },
      gastronomia: {
        lead: 'La gastronomía peruana no solo se *reconoce*. Se *busca*.',
        body: 'La costa concentra algunos de los destinos culinarios más valorados del mundo, atrayendo turismo constante durante todo el año.',
        cierre: 'Este flujo no solo crea experiencias: genera movimiento, dinamiza la economía local y convierte cada ubicación en una *oportunidad real para vivir o invertir*.',
      },
      ciudades: {
        lede: 'Cada región y cada ciudad del Perú concentra una biodiversidad única que impulsa el turismo y la demanda internacional.',
        punch: 'Distintas formas de vivir. Mejores formas de invertir.',
      },
    },
  },

  sierra: {
    nombre: 'Sierra',
    color: '#C9A961',
    quechua_num: 'ꟼ Huk',
    quechua_gast: 'ꟼ Iskay · Mikhuna',
    quechua_viv: 'ꟼ Kimsa · Urqu Kawsay',
    hook_title: 'La espalda del mundo andino',
    hook_lede: 'Desde los 1.500 a los 4.500 metros, diez ciudades milenarias, el corazón del imperio inca y la despensa genética más rica del planeta.',
    intro: {
      eyebrow: 'ꟼ Por qué la Sierra',
      titular: 'Cultura milenaria con *rentabilidad presente*.',
      parrafo: 'La sierra peruana es la espalda del mundo andino, donde el tiempo se mide en generaciones y el aire se respira a cuatro mil metros. Aquí el Imperio Inca dejó su ombligo — Cusco, centro del universo andino — y el quechua se habla en los mismos valles desde hace mil quinientos años.',
      cierre: 'Vivir en la sierra peruana es sumar altura a tu vida. Despertar con vista al Misti, cenar al lado del Titicaca, mirar cóndores planear sobre el Colca. El silencio más hondo del planeta con la cocina más antigua.',
      pilares: ['Imperio Inca vivo', '4.000 variedades de papa', '300 días de sol andino', '10 ciudades milenarias'],
    },
    intro_slides: [
      { label: 'Danzas',      caption: 'Danza de tijeras · UNESCO inmaterial',          img: 'https://images.unsplash.com/photo-1580619305218-8423a7ef79b4?w=1100&q=80' },
      { label: 'Cultura',     caption: 'Machu Picchu · nueva maravilla del mundo',       img: 'https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=1100&q=80' },
      { label: 'Clima',       caption: 'Valle Sagrado · aire puro a 3.000 m',            img: 'https://images.unsplash.com/photo-1526712318848-5f38e2740d77?w=1100&q=80' },
      { label: 'Gastronomía', caption: 'Cuy al horno · cocina inca de cinco siglos',     img: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=1100&q=80' },
    ],
    cultura: {
      patrimonio: ['Cusco · Ombligo del mundo (UNESCO)', 'Machu Picchu (UNESCO)', 'Chavín de Huántar (UNESCO)', 'Centro histórico de Arequipa (UNESCO)'],
      festividades: ['Inti Raymi · 24 junio', 'Virgen de la Candelaria · febrero', 'Semana Santa de Ayacucho', 'Corpus Christi de Cusco'],
      idiomas: ['Español', 'Quechua', 'Aimara'],
      artesania: ['Textiles de alpaca (Chinchero, Taquile)', 'Cerámica de Pucará', 'Plata cusqueña labrada', 'Retablo ayacuchano'],
    },
    turismo: [
      { nombre: 'Baños del Inca & Cumbemayo · Cajamarca', cityId: 'cajamarca',    tipo: 'Cultural',     desc: 'Termales del último Inca y acueductos preincaicos tallados en piedra hace 3.000 años.',           tiempo: '2 — 3 días', img: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=900&q=80' },
      { nombre: 'Cordillera Blanca & Huascarán · Huaraz', cityId: 'ancash',       tipo: 'Aventura',     desc: 'Conjunto de glaciares tropicales más alto del planeta. 33 cumbres por encima de los 5.500m.',     tiempo: '4 — 7 días', img: 'assets/turismo-costa/ancash.png' },
      { nombre: 'Templo de Kotosh · Huánuco',             cityId: 'huanuco',      tipo: 'Arqueológico', desc: 'Las Manos Cruzadas, una de las primeras esculturas de América (2000 a.C.). 4.000 años de historia.', tiempo: '1 — 2 días', img: 'https://images.unsplash.com/photo-1580619305218-8423a7ef79b4?w=900&q=80' },
      { nombre: 'Bosque de Rocas de Huayllay · Pasco',    cityId: 'pasco',        tipo: 'Natural',      desc: 'Formaciones líticas únicas, Reserva Junín y la laguna Chinchaycocha sobre los 4.000 metros.',       tiempo: '2 días',     img: 'https://images.unsplash.com/photo-1531968455001-5c5272a41129?w=900&q=80' },
      { nombre: 'Convento de Ocopa · Huancayo',           cityId: 'junin',        tipo: 'Cultural',     desc: 'Joya colonial del siglo XVIII y feria dominical más antigua del Perú. Valle del Mantaro.',          tiempo: '2 — 3 días', img: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=900&q=80' },
      { nombre: 'Mina de Santa Bárbara · Huancavelica',   cityId: 'huancavelica', tipo: 'Cultural',     desc: 'Sitio histórico colonial, aguas termales de Sacsamarca y comunidades quechua-hablantes vivas.',     tiempo: '2 días',     img: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=900&q=80' },
      { nombre: 'Semana Santa & Wari · Ayacucho',         cityId: 'ayacucho',     tipo: 'Cultural',     desc: 'La Semana Santa más bella del Perú y el sitio arqueológico de Wari, primer imperio andino.',        tiempo: '4 — 7 días', img: 'https://images.unsplash.com/photo-1533929736458-ca588d08c8be?w=900&q=80' },
      { nombre: 'Cañón del Apurímac · Abancay',           cityId: 'apurimac',     tipo: 'Aventura',     desc: 'Uno de los cañones más profundos de América, Santuario del Ampay y ruta del Qhapac Ñan.',          tiempo: '3 — 4 días', img: 'https://images.unsplash.com/photo-1531968455001-5c5272a41129?w=900&q=80' },
      { nombre: 'Machu Picchu · Cusco',                   cityId: 'cusco',        tipo: 'Arqueológico', desc: 'Nueva maravilla del mundo. Ciudadela inca del siglo XV sobre el cañón del Urubamba.',              tiempo: '3 — 5 días', img: 'https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=900&q=80' },
      { nombre: 'Lago Titicaca & Uros · Puno',            cityId: 'puno',         tipo: 'Natural',      desc: 'Lago navegable más alto del mundo. Islas flotantes de los Uros, Taquile (UNESCO) y Amantaní.',     tiempo: '2 — 3 días', img: 'https://images.unsplash.com/photo-1580619305218-8423a7ef79b4?w=900&q=80' },
      { nombre: 'Cañón del Colca & Yanahuara · Arequipa', cityId: 'arequipa',     tipo: 'Natural',      desc: 'Segundo cañón más profundo del mundo. Cóndores al amanecer y arcos de sillar con vista al Misti.',  tiempo: '3 — 5 días', img: 'assets/turismo-costa/arequipa.png' },
    ],
    gastronomia: [
      { nombre: 'Chicharrón con mote',       cityId: 'cajamarca',    desc: 'Cerdo crocante dorado en su propia grasa, acompañado de mote, papa sancochada y salsa criolla.', donde: 'Cajamarca',     img: 'assets/gastronomia-sierra/cajamarca.png' },
      { nombre: 'Pachamanca de cordero',     cityId: 'ancash',       desc: 'Cordero y tubérculos cocidos bajo tierra con piedras calientes y muña. Tradición ancashina.',     donde: 'Huaraz',         img: 'assets/gastronomia-sierra/ancash.png' },
      { nombre: 'Caldo de cabeza',           cityId: 'huanuco',      desc: 'Caldo concentrado de cabeza de cordero con mote, papa nativa, choclo y hierbas andinas.',         donde: 'Huánuco',        img: 'assets/gastronomia-sierra/huanuco.png' },
      { nombre: 'Caldo de gallina',          cityId: 'pasco',        desc: 'Caldo sustancioso de gallina criada en altura, con fideo, papa, choclo y huevo. Reparador del frío andino.', donde: 'Cerro de Pasco', img: 'assets/gastronomia-sierra/pasco.png' },
      { nombre: 'Papa a la huancaína',       cityId: 'junin',        desc: 'Papa amarilla con crema de ají amarillo, queso fresco y galleta de soda. Origen huancaíno.',     donde: 'Huancayo',       img: 'assets/gastronomia-sierra/junin.png' },
      { nombre: 'Mondongo huancavelicano',   cityId: 'huancavelica', desc: 'Sopa ancestral con mote, panza, carne y especias andinas. Plato ceremonial de altura.',          donde: 'Huancavelica',   img: 'assets/gastronomia-sierra/huancavelica.png' },
      { nombre: 'Puchero ayacuchano',        cityId: 'ayacucho',     desc: 'Cordero, col, garbanzos, papa y camote en caldo de carnaval. Plato emblema regional.',           donde: 'Ayacucho',       img: 'assets/gastronomia-sierra/ayacucho.png' },
      { nombre: 'Cuy chactado',              cityId: 'apurimac',     desc: 'Cuy criado en altura, frito y aplastado con piedra caliente. Se sirve con papa, mote y cancha tostada.', donde: 'Abancay',     img: 'assets/gastronomia-sierra/apurimac.png' },
      { nombre: 'Chiriuchu cusqueño',        cityId: 'cusco',        desc: 'Plato ceremonial del Corpus Christi: cuy, gallina, chorizo, cochayuyo y rocoto.',                donde: 'Cusco',          img: 'assets/gastronomia-sierra/cusco.png' },
      { nombre: 'Chairo puneño',             cityId: 'puno',         desc: 'Sopa-estofado del altiplano con cordero, chuño, papa nativa, maní y verduras. Plato emblema del frío puneño.', donde: 'Puno',         img: 'assets/gastronomia-sierra/puno.png' },
      { nombre: 'Rocoto relleno',            cityId: 'arequipa',     desc: 'Rocoto rojo arequipeño relleno de carne, maní y queso, gratinado al horno con pastel de papa.', donde: 'Arequipa',       img: 'assets/gastronomia-sierra/arequipa.png' },
    ],
    beneficios: [
      { icon: 'sun',    titulo: '300 días de sol andino',        desc: 'Cielos azules, aire seco y limpio. Del frío costero de Lima al sol constante a 3.000m.' },
      { icon: 'shield', titulo: 'Ciudades de baja criminalidad', desc: 'Cusco, Arequipa, Ayacucho con índices menores que capitales europeas. Policía turística dedicada.' },
      { icon: 'med',    titulo: 'Clínicas especializadas',       desc: 'San Juan de Dios, MAC, Pardo. Universidades médicas centenarias en Cusco y Arequipa.' },
      { icon: 'heart',  titulo: 'Comunidad internacional',       desc: 'Más de 5.000 europeos residiendo. Expatriados activos en Cusco, Arequipa y Puno.' },
      { icon: 'euro',   titulo: 'Coste de vida 52% menor',       desc: 'Alquiler céntrico 500-700€. Almuerzo típico 5-8€. Energía y transporte económicos.' },
      { icon: 'plane',  titulo: 'Aeropuertos internacionales',   desc: 'Cusco y Arequipa: vuelos directos a Lima, Bogotá, Santiago. 1h a Lima.' },
      { icon: 'wifi',   titulo: 'Fibra 300 Mb extendida',        desc: 'Cobertura total en capitales. Co-workings Selina, Qorikancha, Tribal.' },
      { icon: 'edu',    titulo: 'Universidades centenarias',     desc: 'UNSAAC (Cusco), UNSA (Arequipa), UNSCH (Ayacucho). Excelencia académica andina.' },
    ],
    quotes: {
      cultura: {
        lead: 'Donde el *patrimonio* se vive, el *valor* no caduca.',
        body: 'La sierra peruana alberga el corazón del Imperio Inca, cinco sitios UNESCO y un calendario de festividades — Inti Raymi, Corpus Christi, Candelaria — que convierte casi cada mes del año en temporada alta turística.',
        cierre: 'Comprar aquí no es entrar a un mercado: es heredar un *activo cultural que se revaloriza solo*.',
      },
      gastronomia: {
        lead: 'La despensa más *diversa* del planeta está a *4.000 metros*.',
        body: 'Cuatro mil variedades de papa, tres mil de quinua, alpaca, trucha andina y una cocina — pachamanca, cuy, rocoto relleno, chiriuchu — que ha elevado los ingredientes andinos a las cartas de los mejores restaurantes del mundo.',
        cierre: 'Cada valle, cada mercado y cada picantería atraen un turismo que busca *autenticidad con altura* — un argumento que sostiene el valor inmobiliario de cada ciudad andina.',
      },
      ciudades: {
        lede: 'Cada ciudad andina combina altura, patrimonio vivo y circuitos turísticos consolidados — Cusco, Machu Picchu, Colca, Titicaca — que sostienen la demanda internacional durante todo el año.',
        punch: 'Vivir entre montañas. Invertir en historia.',
      },
    },
  },

  selva: {
    nombre: 'Selva',
    color: '#7FB069',
    quechua_num: 'ꟼ Huk',
    quechua_gast: 'ꟼ Iskay · Mikhuna',
    quechua_viv: 'ꟼ Kimsa · Sach\'a Kawsay',
    hook_title: 'El pulmón verde del continente',
    hook_lede: 'Sesenta por ciento del territorio peruano, cuatro ciudades amazónicas, el 11% de los bosques del mundo y la mayor biodiversidad por metro cuadrado del planeta.',
    intro: {
      eyebrow: 'ꟼ Por qué la Selva',
      titular: 'Biodiversidad como *activo de futuro*.',
      parrafo: 'La selva peruana ocupa el sesenta por ciento del territorio pero es, curiosamente, la más desconocida. Aquí está el once por ciento de los bosques del mundo, la mayor concentración de biodiversidad jamás medida y los pueblos originarios Shipibo, Asháninka y Awajún con su sabiduría milenaria sobre plantas medicinales.',
      cierre: 'Vivir en la selva peruana es vivir con el ritmo del agua. Canoa al amanecer, orquídeas en el jardín, cena bajo un cielo de estrellas sin contaminación lumínica. La aventura perpetua — y la vida más sostenible que existe.',
      pilares: ['11% de bosques del mundo', 'Biodiversidad récord', 'Ayahuasca ancestral', 'Aire más puro del planeta'],
    },
    intro_slides: [
      { label: 'Danzas',      caption: 'Danza de la anaconda · ritual amazónico',       img: 'https://images.unsplash.com/photo-1516036438522-1ae2c66c8d9e?w=1100&q=80' },
      { label: 'Cultura',     caption: 'Arte Shipibo · patrón kené ancestral',           img: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=1100&q=80' },
      { label: 'Clima',       caption: 'Río Amazonas · bosque siempre verde',            img: 'https://images.unsplash.com/photo-1523867904473-6da7ce7ed00c?w=1100&q=80' },
      { label: 'Gastronomía', caption: 'Juane amazónico · arroz, gallina y bijao',       img: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=1100&q=80' },
    ],
    cultura: {
      patrimonio: ['Parque Nacional del Manu (UNESCO)', 'Reserva Nacional Pacaya-Samiria', 'Parque Nacional Tingo María', 'Danza Pucllay (UNESCO inmaterial)'],
      festividades: ['Fiesta de San Juan · 24 junio', 'Carnaval amazónico · febrero', 'Ayahuasca tradicional todo el año', 'Fiesta de la Trucha · agosto'],
      idiomas: ['Español', 'Shipibo-Conibo', 'Asháninka', 'Awajún', 'Quechua amazónico'],
      artesania: ['Tejidos Shipibo kené', 'Semillas y huayruros', 'Máscaras de chonta', 'Madera tallada amazónica'],
    },
    turismo: [
      { nombre: 'Kuélap & Catarata Gocta · Chachapoyas',  cityId: 'amazonas',       tipo: 'Arqueológico', desc: 'La fortaleza del norte (siglo IX) y la tercera catarata más alta del mundo (771 metros).',     tiempo: '4 — 5 días', img: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=900&q=80' },
      { nombre: 'Pacaya-Samiria & Belén · Iquitos',       cityId: 'loreto',         tipo: 'Natural',  desc: 'Mayor reserva de Amazonía inundable del mundo y el mítico mercado flotante de Belén.',             tiempo: '4 — 6 días', img: 'https://images.unsplash.com/photo-1523867904473-6da7ce7ed00c?w=900&q=80' },
      { nombre: 'Alto Mayo & Cataratas · Moyobamba',      cityId: 'san-martin',     tipo: 'Natural',  desc: 'Ciudad de las orquídeas, 2.500 especies, cataratas Gera, Lahuarpia y aguas termales.',             tiempo: '3 — 4 días', img: 'https://images.unsplash.com/photo-1485470733090-0aae1788d5af?w=900&q=80' },
      { nombre: 'Yarinacocha & Shipibo · Pucallpa',       cityId: 'ucayali',        tipo: 'Cultural', desc: 'Lago paradisíaco, comunidades Shipibo-Conibo y arte kené reconocido internacionalmente.',           tiempo: '3 días',     img: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=900&q=80' },
      { nombre: 'Tambopata & Manu · Puerto Maldonado',    cityId: 'madre-de-dios',  tipo: 'Natural',  desc: 'Mayor concentración de biodiversidad por metro cuadrado del planeta. Collpa de guacamayos.',         tiempo: '4 — 6 días', img: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=900&q=80' },
    ],
    gastronomia: [
      { nombre: 'Café chachapoyano',       cityId: 'amazonas',       desc: 'Café orgánico de altura con denominación de origen, premiado en concursos internacionales.',         donde: 'Chachapoyas',       img: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=700&q=80' },
      { nombre: 'Juane amazónico',         cityId: 'loreto',         desc: 'Arroz con gallina, huevo, aceituna y especias envuelto en hoja de bijao. Plato ritual de San Juan.', donde: 'Iquitos',           img: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=700&q=80' },
      { nombre: 'Inchicapi de Moyobamba',  cityId: 'san-martin',     desc: 'Sopa espesa de gallina con maní tostado, yuca, sacha culantro y harina de maíz molida.',             donde: 'Moyobamba',         img: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=700&q=80' },
      { nombre: 'Tacacho con cecina',      cityId: 'ucayali',        desc: 'Plátano verde asado y machacado con manteca, acompañado de carne seca ahumada de Pucallpa.',          donde: 'Pucallpa',          img: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=700&q=80' },
      { nombre: 'Patarashca de paiche',    cityId: 'madre-de-dios',  desc: 'Pescado amazónico envuelto en hoja de bijao, asado a la brasa con ajos y plátano maduro.',            donde: 'Puerto Maldonado',  img: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=700&q=80' },
    ],
    beneficios: [
      { icon: 'sun',    titulo: 'Clima tropical constante',       desc: 'Entre 22° y 32°C todo el año. Lluvias nutridas, aire húmedo, bosque siempre verde.' },
      { icon: 'heart',  titulo: 'Vida en contacto con la naturaleza', desc: 'Bosque primario a minutos de las ciudades. Río, canoa, fauna al alcance diario.' },
      { icon: 'euro',   titulo: 'Coste de vida 58% menor',        desc: 'Alquileres desde 300€, mercados locales generosos, economía familiar y sostenible.' },
      { icon: 'shield', titulo: 'Ciudades pequeñas y tranquilas', desc: 'Iquitos, Tarapoto, Puerto Maldonado con ritmo relajado y comunidades acogedoras.' },
      { icon: 'wifi',   titulo: 'Fibra óptica en capitales',       desc: 'Iquitos, Pucallpa, Tarapoto con buena conectividad a pesar del aislamiento geográfico.' },
      { icon: 'med',    titulo: 'Medicina ancestral + moderna',   desc: 'Clínicas regionales + conocimiento tradicional amazónico reconocido mundialmente.' },
      { icon: 'plane',  titulo: 'Vuelos diarios a Lima',           desc: 'Iquitos 1h30, Pucallpa 1h, Tarapoto 1h10, Puerto Maldonado 1h40.' },
      { icon: 'edu',    titulo: 'Universidades amazónicas',        desc: 'UNAP (Iquitos), UNU (Pucallpa), UNSM (Tarapoto). Programas virtuales internacionales.' },
    ],
    quotes: {
      cultura: {
        lead: 'Donde las *tradiciones* siguen vivas, la cultura no se *museiza*: se visita.',
        body: 'La selva peruana conserva pueblos originarios — Shipibo, Asháninka, Awajún —, arte kené, rituales de San Juan, ayahuasca tradicional y conocimiento medicinal milenario que convierten cada viaje en una experiencia irrepetible.',
        cierre: 'Invertir en la Amazonía es apostar por *la última frontera del turismo consciente* — experiencias que el viajero europeo ya no encuentra en su continente.',
      },
      gastronomia: {
        lead: 'Aquí cada *ingrediente* existe solo en *un lugar del mundo*.',
        body: 'Paiche, cocona, aguaje, camu camu, ají charapita, sacha inchi: ingredientes endémicos que están poniendo la cocina amazónica en las cartas de los mejores restaurantes globales — juane, tacacho, patarashca, inchicapi.',
        cierre: 'La selva atrae cada año más viajeros en busca de sabores inéditos — un flujo creciente que consolida su valor *turístico, residencial y de inversión*.',
      },
      ciudades: {
        lede: 'Cada ciudad amazónica es una puerta distinta al mismo bioma — Iquitos sobre el Amazonas, Tarapoto entre cascadas, Puerto Maldonado frente al Manu — el destino de eco-turismo con mayor proyección internacional.',
        punch: 'Vivir con el río. Invertir en lo irrepetible.',
      },
    },
  },
};

window.MACRO_REGION_DATA = MACRO_REGION_DATA;
