// General content per macro-region (Costa / Sierra / Selva) — meant to inspire
// the user to click into a specific city card. City-exclusive content lives in
// the per-city pages (to be built).
const MACRO_REGION_DATA = {
  costa: {
    nombre: 'Costa',
    color: '#6FA8C9',
    quechua_num: 'ꟼ Huk',
    quechua_gast: 'ꟼ Iskay · Mikhuna',
    quechua_viv: 'ꟼ Kimsa · Qucha Kawsay',
    hook_title: 'Desde los manglares hasta el desierto del sur',
    hook_lede: 'Dos mil kilómetros de Pacífico, once ciudades costeras, la cocina más reconocida del mundo y el clima más templado de Sudamérica.',
    intro: {
      eyebrow: 'ꟼ Por qué la Costa',
      titular: 'Pacífico, desierto y la *cocina* más admirada del mundo.',
      parrafo: 'La costa peruana no es una línea entre dos tierras. Es una civilización propia. Aquí nacieron las culturas Moche, Chimú, Paracas y Nazca hace tres mil años, tejiendo textiles que hoy siguen siendo inigualables y levantando templos que aún desafían al tiempo.',
      cierre: 'Vivir aquí es despertar con el olor del mar, comer un ceviche al mediodía y brindar con pisco viendo el sol caer sobre el Pacífico. Un lujo que ya no existe en Europa.',
      pilares: ['3000 años de cultura', 'Capital gastronómica', '300 días de sol', '12h directo a Madrid'],
    },
    intro_slides: [
      { label: 'Danzas',      caption: 'Marinera norteña · baile nacional',           img: 'https://images.unsplash.com/photo-1515169067868-5387ec356754?w=1100&q=80' },
      { label: 'Cultura',     caption: 'Centro histórico de Lima · UNESCO',            img: 'https://images.unsplash.com/photo-1531065208531-4036c0dba3ca?w=1100&q=80' },
      { label: 'Clima',       caption: 'Malecón de Miraflores · Pacífico templado',    img: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1100&q=80' },
      { label: 'Gastronomía', caption: 'Ceviche del día · limón, ají limo, cebolla',   img: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=1100&q=80' },
    ],
    cultura: {
      patrimonio: ['Caral · ciudad más antigua de América (UNESCO)', 'Líneas de Nazca (UNESCO)', 'Chan Chan (UNESCO)', 'Centro histórico de Lima (UNESCO)', 'Señor de Sipán'],
      festividades: ['Señor de los Milagros · octubre', 'Fiesta de la Vendimia · marzo', 'Aniversario de Lima · enero', 'Semana jubilar de Trujillo'],
      idiomas: ['Español', 'Quechua (minoritario)'],
      artesania: ['Platería limeña', 'Cerámica Chancay', 'Textil Paracas', 'Joyería Chimú'],
    },
    turismo: [
      { nombre: 'Máncora · Piura',           tipo: 'Playa',          desc: 'Capital del surf peruano, oleaje constante y vida bohemia al borde del Pacífico.',    tiempo: '5 — 7 días', img: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=80' },
      { nombre: 'Paracas & Ballestas',       tipo: 'Natural',        desc: 'Galápagos peruano: lobos marinos, pingüinos Humboldt y la Reserva Nacional.',         tiempo: '2 — 3 días', img: 'https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?w=900&q=80' },
      { nombre: 'Líneas de Nazca · Ica',     tipo: 'Arqueológico',   desc: 'Geoglifos milenarios solo visibles desde el aire. Patrimonio UNESCO.',                 tiempo: '1 — 2 días', img: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=900&q=80' },
      { nombre: 'Chan Chan · La Libertad',   tipo: 'Arqueológico',   desc: 'Mayor ciudad de barro del mundo precolombino, construida por los Chimú.',               tiempo: '1 día',      img: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=900&q=80' },
      { nombre: 'Miraflores & Barranco',     tipo: 'Urbano',         desc: 'Malecón sobre el Pacífico, vida nocturna, arte callejero, cocina de autor.',           tiempo: '3 — 5 días', img: 'https://images.unsplash.com/photo-1531065208531-4036c0dba3ca?w=900&q=80' },
      { nombre: 'Huacachina · Ica',          tipo: 'Aventura',       desc: 'Único oasis del desierto peruano, sandboarding y vino pisco.',                          tiempo: '2 días',     img: 'https://images.unsplash.com/photo-1604909053522-f6bae95b1c82?w=900&q=80' },
    ],
    gastronomia: [
      { nombre: 'Ceviche',           desc: 'Pescado del día, limón sutil, ají limo, cebolla morada, camote y choclo.',       donde: 'Lima · Trujillo · Piura',      img: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=700&q=80' },
      { nombre: 'Pisco Sour',        desc: 'Cóctel nacional: pisco quebranta, limón verde, clara de huevo y amargo.',        donde: 'Lima · Ica · Moquegua',        img: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=700&q=80' },
      { nombre: 'Causa limeña',      desc: 'Papa amarilla prensada con ají, cebolla y relleno de pollo, atún o cangrejo.',   donde: 'Lima',                         img: 'https://images.unsplash.com/photo-1604909053522-f6bae95b1c82?w=700&q=80' },
      { nombre: 'Tiradito',          desc: 'Pescado en finas láminas con crema de ají amarillo — fusión nikkei peruana.',    donde: 'Lima · Miraflores',            img: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=700&q=80' },
      { nombre: 'Cabrito norteño',   desc: 'Cabrito tierno macerado en chicha de jora, con frijoles y arroz.',               donde: 'Piura · Lambayeque',           img: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=700&q=80' },
      { nombre: 'Chupe de camarones',desc: 'Sopa espesa de camarones de río con huevo, queso y rocoto.',                      donde: 'Arequipa · Ica',               img: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=700&q=80' },
    ],
    beneficios: [
      { icon: 'sun',    titulo: 'Clima templado todo el año', desc: 'Entre 16° y 28°C del norte al sur. Sin frío europeo, sin calor extremo. 300+ días de sol.' },
      { icon: 'plane',  titulo: 'Hub aéreo directo a Europa', desc: 'Aeropuerto Jorge Chávez: vuelo directo a Madrid 12h. Conexión a toda América.' },
      { icon: 'med',    titulo: 'Red hospitalaria de primer nivel', desc: 'Clínicas Anglo Americana, Delgado, San Felipe. Cobertura con seguros internacionales.' },
      { icon: 'wifi',   titulo: 'Fibra óptica 500 Mb',         desc: 'Infraestructura top del continente. Hubs tecnológicos en Lima y Arequipa.' },
      { icon: 'euro',   titulo: 'Coste de vida 42% menor',     desc: 'Sueldo madrileño rinde como 4.830€. Restaurantes Michelin a un tercio del precio.' },
      { icon: 'edu',    titulo: 'Colegios europeos',            desc: 'Alexander von Humboldt, Franco Peruano, San Silvestre. Universidades privadas top.' },
      { icon: 'heart',  titulo: '30.000 españoles en la costa', desc: 'Instituto Cervantes, Cámara España-Perú, comunidad consolidada.' },
      { icon: 'shield', titulo: 'Distritos premium seguros',    desc: 'Miraflores, San Isidro, Yanahuara con seguridad 24/7 y patrullaje municipal.' },
    ],
  },

  sierra: {
    nombre: 'Sierra',
    color: '#C9A961',
    quechua_num: 'ꟼ Huk',
    quechua_gast: 'ꟼ Iskay · Mikhuna',
    quechua_viv: 'ꟼ Kimsa · Urqu Kawsay',
    hook_title: 'La espalda del mundo andino',
    hook_lede: 'Desde los 1.500 a los 4.500 metros, diez ciudades milenarias, el corazón del imperio inca y la despensa genética más rica del planeta.',
    intro: {
      eyebrow: 'ꟼ Por qué la Sierra',
      titular: 'La columna vertebral del *continente americano*.',
      parrafo: 'La sierra peruana es la espalda del mundo andino, donde el tiempo se mide en generaciones y el aire se respira a cuatro mil metros. Aquí el Imperio Inca dejó su ombligo — Cusco, centro del universo andino — y el quechua se habla en los mismos valles desde hace mil quinientos años.',
      cierre: 'Vivir en la sierra peruana es sumar altura a tu vida. Despertar con vista al Misti, cenar al lado del Titicaca, mirar cóndores planear sobre el Colca. El silencio más hondo del planeta con la cocina más antigua.',
      pilares: ['Imperio Inca vivo', '4.000 variedades de papa', '300 días de sol andino', '10 ciudades milenarias'],
    },
    intro_slides: [
      { label: 'Danzas',      caption: 'Danza de tijeras · UNESCO inmaterial',          img: 'https://images.unsplash.com/photo-1580619305218-8423a7ef79b4?w=1100&q=80' },
      { label: 'Cultura',     caption: 'Machu Picchu · nueva maravilla del mundo',       img: 'https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=1100&q=80' },
      { label: 'Clima',       caption: 'Valle Sagrado · aire puro a 3.000 m',            img: 'https://images.unsplash.com/photo-1526712318848-5f38e2740d77?w=1100&q=80' },
      { label: 'Gastronomía', caption: 'Cuy al horno · cocina inca de cinco siglos',     img: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=1100&q=80' },
    ],
    cultura: {
      patrimonio: ['Cusco · Ombligo del mundo (UNESCO)', 'Machu Picchu (UNESCO)', 'Chavín de Huántar (UNESCO)', 'Centro histórico de Arequipa (UNESCO)'],
      festividades: ['Inti Raymi · 24 junio', 'Virgen de la Candelaria · febrero', 'Semana Santa de Ayacucho', 'Corpus Christi de Cusco'],
      idiomas: ['Español', 'Quechua', 'Aimara'],
      artesania: ['Textiles de alpaca (Chinchero, Taquile)', 'Cerámica de Pucará', 'Plata cusqueña labrada', 'Retablo ayacuchano'],
    },
    turismo: [
      { nombre: 'Machu Picchu · Cusco',      tipo: 'Arqueológico',   desc: 'Nueva maravilla del mundo. Ciudadela inca del siglo XV sobre el cañón del Urubamba.', tiempo: '2 — 3 días',  img: 'https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=900&q=80' },
      { nombre: 'Cañón del Colca · Arequipa',tipo: 'Natural',        desc: 'Segundo cañón más profundo del mundo, cóndores al amanecer sobre la Cruz del Cóndor.',tiempo: '2 días',      img: 'https://images.unsplash.com/photo-1543349689-9a4d426bee8e?w=900&q=80' },
      { nombre: 'Lago Titicaca · Puno',      tipo: 'Natural',        desc: 'Lago navegable más alto del mundo. Islas flotantes de los Uros, Taquile y Amantaní.',   tiempo: '2 — 3 días',  img: 'https://images.unsplash.com/photo-1580619305218-8423a7ef79b4?w=900&q=80' },
      { nombre: 'Valle Sagrado · Cusco',     tipo: 'Cultural',       desc: 'Pisac, Ollantaytambo, Chinchero — los pueblos incas siguen vivos, telares y mercados.',tiempo: '2 — 3 días',  img: 'https://images.unsplash.com/photo-1533929736458-ca588d08c8be?w=900&q=80' },
      { nombre: 'Cordillera Blanca · Áncash',tipo: 'Aventura',       desc: 'Huascarán 6.768m, Laguna 69, trekking clásico de Santa Cruz. 33 cumbres sobre 5.500m.',tiempo: '4 — 7 días',  img: 'https://images.unsplash.com/photo-1526712318848-5f38e2740d77?w=900&q=80' },
      { nombre: 'Vinicunca · Cusco',         tipo: 'Natural',        desc: 'Montaña de 7 colores a 5.200 metros, geología pintada por minerales.',                  tiempo: '1 día',       img: 'https://images.unsplash.com/photo-1531968455001-5c5272a41129?w=900&q=80' },
    ],
    gastronomia: [
      { nombre: 'Cuy al horno',      desc: 'Plato milenario andino: cuy entero crujiente con papas nativas y huacatay.',      donde: 'Cusco · Arequipa · Ayacucho',  img: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=700&q=80' },
      { nombre: 'Rocoto relleno',    desc: 'Rocoto rojo picante con carne, pasas, queso andino y huevo gratinado.',           donde: 'Arequipa',                     img: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=700&q=80' },
      { nombre: 'Pachamanca',        desc: 'Carnes y tubérculos cocidos bajo tierra con piedras calientes y hierbas.',        donde: 'Junín · Huancavelica',         img: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=700&q=80' },
      { nombre: 'Chiriuchu',         desc: 'Plato ceremonial del Corpus Christi cusqueño: cuy, gallina, chorizo, cochayuyo.',  donde: 'Cusco',                        img: 'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=700&q=80' },
      { nombre: 'Papa a la huancaína',desc:'Papa amarilla con crema de ají amarillo, queso fresco y galleta de soda.',         donde: 'Junín',                        img: 'https://images.unsplash.com/photo-1601593246562-287ed4e0ad14?w=700&q=80' },
      { nombre: 'Trucha andina',     desc: 'Trucha fresca de río o laguna, frita o al ajo con papa nativa.',                   donde: 'Puno · Cusco · Junín',         img: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=700&q=80' },
    ],
    beneficios: [
      { icon: 'sun',    titulo: '300 días de sol andino',        desc: 'Cielos azules, aire seco y limpio. Del frío costero de Lima al sol constante a 3.000m.' },
      { icon: 'shield', titulo: 'Ciudades de baja criminalidad', desc: 'Cusco, Arequipa, Ayacucho con índices menores que capitales europeas. Policía turística dedicada.' },
      { icon: 'med',    titulo: 'Clínicas especializadas',       desc: 'San Juan de Dios, MAC, Pardo. Universidades médicas centenarias en Cusco y Arequipa.' },
      { icon: 'heart',  titulo: 'Comunidad internacional',       desc: 'Más de 5.000 europeos residiendo. Expatriados activos en Cusco, Arequipa y Puno.' },
      { icon: 'euro',   titulo: 'Coste de vida 52% menor',       desc: 'Alquiler céntrico 500-700€. Almuerzo típico 5-8€. Energía y transporte económicos.' },
      { icon: 'plane',  titulo: 'Aeropuertos internacionales',   desc: 'Cusco y Arequipa: vuelos directos a Lima, Bogotá, Santiago. 1h a Lima.' },
      { icon: 'wifi',   titulo: 'Fibra 300 Mb extendida',        desc: 'Cobertura total en capitales. Co-workings Selina, Qorikancha, Tribal.' },
      { icon: 'edu',    titulo: 'Universidades centenarias',     desc: 'UNSAAC (Cusco), UNSA (Arequipa), UNSCH (Ayacucho). Excelencia académica andina.' },
    ],
  },

  selva: {
    nombre: 'Selva',
    color: '#7FB069',
    quechua_num: 'ꟼ Huk',
    quechua_gast: 'ꟼ Iskay · Mikhuna',
    quechua_viv: 'ꟼ Kimsa · Sach\'a Kawsay',
    hook_title: 'El pulmón verde del continente',
    hook_lede: 'Sesenta por ciento del territorio peruano, cuatro ciudades amazónicas, el 11% de los bosques del mundo y la mayor biodiversidad por metro cuadrado del planeta.',
    intro: {
      eyebrow: 'ꟼ Por qué la Selva',
      titular: 'El *pulmón verde* más valioso del planeta.',
      parrafo: 'La selva peruana ocupa el sesenta por ciento del territorio pero es, curiosamente, la más desconocida. Aquí está el once por ciento de los bosques del mundo, la mayor concentración de biodiversidad jamás medida y los pueblos originarios Shipibo, Asháninka y Awajún con su sabiduría milenaria sobre plantas medicinales.',
      cierre: 'Vivir en la selva peruana es vivir con el ritmo del agua. Canoa al amanecer, orquídeas en el jardín, cena bajo un cielo de estrellas sin contaminación lumínica. La aventura perpetua — y la vida más sostenible que existe.',
      pilares: ['11% de bosques del mundo', 'Biodiversidad récord', 'Ayahuasca ancestral', 'Aire más puro del planeta'],
    },
    intro_slides: [
      { label: 'Danzas',      caption: 'Danza de la anaconda · ritual amazónico',       img: 'https://images.unsplash.com/photo-1516036438522-1ae2c66c8d9e?w=1100&q=80' },
      { label: 'Cultura',     caption: 'Arte Shipibo · patrón kené ancestral',           img: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=1100&q=80' },
      { label: 'Clima',       caption: 'Río Amazonas · bosque siempre verde',            img: 'https://images.unsplash.com/photo-1523867904473-6da7ce7ed00c?w=1100&q=80' },
      { label: 'Gastronomía', caption: 'Juane amazónico · arroz, gallina y bijao',       img: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=1100&q=80' },
    ],
    cultura: {
      patrimonio: ['Parque Nacional del Manu (UNESCO)', 'Reserva Nacional Pacaya-Samiria', 'Parque Nacional Tingo María', 'Danza Pucllay (UNESCO inmaterial)'],
      festividades: ['Fiesta de San Juan · 24 junio', 'Carnaval amazónico · febrero', 'Ayahuasca tradicional todo el año', 'Fiesta de la Trucha · agosto'],
      idiomas: ['Español', 'Shipibo-Conibo', 'Asháninka', 'Awajún', 'Quechua amazónico'],
      artesania: ['Tejidos Shipibo kené', 'Semillas y huayruros', 'Máscaras de chonta', 'Madera tallada amazónica'],
    },
    turismo: [
      { nombre: 'Reserva Pacaya-Samiria',    tipo: 'Natural',        desc: 'Mayor reserva de Amazonía inundable del mundo. Delfines rosados, manatíes, caimanes.',tiempo: '4 — 6 días',  img: 'https://images.unsplash.com/photo-1523867904473-6da7ce7ed00c?w=900&q=80' },
      { nombre: 'Parque del Manu',           tipo: 'Natural',        desc: 'Biodiversidad récord: 1.000+ especies de aves, 200 de mamíferos, 15.000 de plantas.',   tiempo: '5 — 8 días',  img: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=900&q=80' },
      { nombre: 'Tambopata',                 tipo: 'Natural',        desc: 'Lagos de herradura, collpa de guacamayos, jaguares y monos araña a orillas del río.',  tiempo: '3 — 4 días',  img: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=900&q=80' },
      { nombre: 'Iquitos & Belén flotante',  tipo: 'Cultural',       desc: 'Casa de Fitzcarraldo, mercado amazónico flotante, crucero por el río Amazonas.',        tiempo: '3 — 5 días',  img: 'https://images.unsplash.com/photo-1516036438522-1ae2c66c8d9e?w=900&q=80' },
      { nombre: 'Alto Mayo · Moyobamba',     tipo: 'Natural',        desc: 'Ciudad de las orquídeas, 2.500 especies, cataratas y aguas termales.',                  tiempo: '2 — 3 días',  img: 'https://images.unsplash.com/photo-1485470733090-0aae1788d5af?w=900&q=80' },
      { nombre: 'Cataratas de Gocta',        tipo: 'Aventura',       desc: 'Tercera catarata más alta del mundo (771m), descubierta por el mundo en 2002.',         tiempo: '2 días',      img: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=900&q=80' },
    ],
    gastronomia: [
      { nombre: 'Juane',             desc: 'Arroz con gallina, huevo, aceituna y especias envuelto en hoja de bijao.',       donde: 'Iquitos · Moyobamba',          img: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=700&q=80' },
      { nombre: 'Tacacho con cecina',desc: 'Plátano verde asado y machacado con manteca, acompañado de carne seca ahumada.', donde: 'Pucallpa · Iquitos',           img: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=700&q=80' },
      { nombre: 'Patarashca',        desc: 'Pescado amazónico (paiche, dorado) envuelto en hoja de bijao y asado a la brasa.',donde: 'Iquitos · Tarapoto',           img: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=700&q=80' },
      { nombre: 'Inchicapi',         desc: 'Sopa espesa de gallina con maní, yuca, sacha culantro y harina de maíz.',         donde: 'San Martín',                   img: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=700&q=80' },
      { nombre: 'Aguajina',          desc: 'Bebida refrescante del fruto aguaje, rica en betacaroteno, sabor dulce-ácido.',   donde: 'Iquitos · Pucallpa',           img: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=700&q=80' },
      { nombre: 'Masato',            desc: 'Bebida fermentada de yuca, ritual amazónico compartido en las comunidades.',      donde: 'Toda la selva',                img: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=700&q=80' },
    ],
    beneficios: [
      { icon: 'sun',    titulo: 'Clima tropical constante',       desc: 'Entre 22° y 32°C todo el año. Lluvias nutridas, aire húmedo, bosque siempre verde.' },
      { icon: 'heart',  titulo: 'Vida en contacto con la naturaleza', desc: 'Bosque primario a minutos de las ciudades. Río, canoa, fauna al alcance diario.' },
      { icon: 'euro',   titulo: 'Coste de vida 58% menor',        desc: 'Alquileres desde 300€, mercados locales generosos, economía familiar y sostenible.' },
      { icon: 'shield', titulo: 'Ciudades pequeñas y tranquilas', desc: 'Iquitos, Tarapoto, Puerto Maldonado con ritmo relajado y comunidades acogedoras.' },
      { icon: 'wifi',   titulo: 'Fibra óptica en capitales',       desc: 'Iquitos, Pucallpa, Tarapoto con buena conectividad a pesar del aislamiento geográfico.' },
      { icon: 'med',    titulo: 'Medicina ancestral + moderna',   desc: 'Clínicas regionales + conocimiento tradicional amazónico reconocido mundialmente.' },
      { icon: 'plane',  titulo: 'Vuelos diarios a Lima',           desc: 'Iquitos 1h30, Pucallpa 1h, Tarapoto 1h10, Puerto Maldonado 1h40.' },
      { icon: 'edu',    titulo: 'Universidades amazónicas',        desc: 'UNAP (Iquitos), UNU (Pucallpa), UNSM (Tarapoto). Programas virtuales internacionales.' },
    ],
  },
};

window.MACRO_REGION_DATA = MACRO_REGION_DATA;
