// Rich region data — culture, tourism, gastronomy, benefits
const REGION_DATA = {
  cusco: {
    nombre: 'Cusco',
    tipo: 'sierra',
    capital: 'Cusco',
    altitud: '3.399 m',
    clima: '10 — 20°C',
    hero: 'https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=1600&q=80',
    imagen_side: 'https://images.unsplash.com/photo-1533929736458-ca588d08c8be?w=1200&q=80',
    tagline: 'Capital del Imperio Inca · Patrimonio UNESCO',
    descripcion: 'Ciudad viva a 3.399 metros donde el pasado inca convive con el presente cosmopolita. Callejuelas empedradas, templos coloniales sobre bases incas, mercados que huelen a coca y pan de maíz.',
    cultura: {
      patrimonio: ['Centro histórico UNESCO (1983)', 'Machu Picchu (2h por tren)', 'Sacsayhuamán, Qoricancha'],
      festivales: ['Inti Raymi · 24 junio', 'Corpus Christi · junio', 'Señor de los Temblores · Semana Santa'],
      idiomas: ['Español', 'Quechua'],
      artesania: ['Textiles de Chinchero', 'Cerámica de Pisac', 'Plata labrada'],
    },
    turismo: [
      { nombre: 'Machu Picchu', tipo: 'Arqueológico', desc: 'La ciudadela inca del siglo XV, nueva maravilla del mundo.', tiempo: '2h tren · 1 día', img: 'https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=800&q=80' },
      { nombre: 'Valle Sagrado', tipo: 'Cultural', desc: 'Pisac, Ollantaytambo, Chinchero — pueblos incas vivos.', tiempo: '1h · 1-2 días', img: 'https://images.unsplash.com/photo-1580619305218-8423a7ef79b4?w=800&q=80' },
      { nombre: 'Montaña de 7 Colores', tipo: 'Natural', desc: 'Vinicunca a 5.200m, geología pintada.', tiempo: '3h · 1 día', img: 'https://images.unsplash.com/photo-1531968455001-5c5272a41129?w=800&q=80' },
      { nombre: 'Camino Inca', tipo: 'Aventura', desc: 'Trekking clásico de 4 días hasta Machu Picchu.', tiempo: '4 días', img: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800&q=80' },
      { nombre: 'San Blas', tipo: 'Barrio bohemio', desc: 'Arte, galerías, miradores sobre la ciudad.', tiempo: 'En ciudad', img: 'https://images.unsplash.com/photo-1533929736458-ca588d08c8be?w=800&q=80' },
      { nombre: 'Laguna Humantay', tipo: 'Natural', desc: 'Laguna turquesa al pie del nevado Salkantay.', tiempo: '3h · 1 día', img: 'https://images.unsplash.com/photo-1526712318848-5f38e2740d77?w=800&q=80' },
    ],
    gastronomia: [
      { nombre: 'Chiriuchu', desc: 'Plato ceremonial del Corpus Christi: cuy, gallina, chorizo, cochayuyo.', donde: 'Picanterías del centro', img: 'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=700&q=80' },
      { nombre: 'Adobo cusqueño', desc: 'Cerdo en chicha de jora y ají panca, tradicional de domingo.', donde: 'La Cusqueñita', img: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=700&q=80' },
      { nombre: 'Trucha del valle', desc: 'Trucha andina fresca, al ajo o frita.', donde: 'Valle Sagrado', img: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=700&q=80' },
      { nombre: 'Choclo con queso', desc: 'Maíz gigante blanco, de grano dulce, con queso andino.', donde: 'Mercado San Pedro', img: 'https://images.unsplash.com/photo-1601593246562-287ed4e0ad14?w=700&q=80' },
      { nombre: 'Chicha morada', desc: 'Maíz morado, piña, canela — refresco ancestral.', donde: 'Todas partes', img: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=700&q=80' },
      { nombre: 'Cuy al horno', desc: 'Plato andino milenario, crujiente y especiado.', donde: 'Pachapapa', img: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=700&q=80' },
    ],
    beneficios: [
      { icon: 'sun', titulo: 'Clima estable todo el año', desc: 'Temperaturas entre 10° y 20°C. Cielos azules en estación seca (abril-octubre).' },
      { icon: 'med', titulo: 'Sistema de salud privado', desc: 'Clínica San Juan de Dios, Pardo y MAC tienen atención en español y seguros internacionales.' },
      { icon: 'wifi', titulo: 'Internet fibra 300Mb', desc: 'Movistar y Claro cubren el centro. Co-working Selina, Qorikancha para remote work.' },
      { icon: 'edu', titulo: 'Colegios internacionales', desc: 'Colegio Franco Peruano, Max Uhle. Comunidad europea creciente.' },
      { icon: 'plane', titulo: 'Conexión internacional', desc: 'Aeropuerto Velasco Astete: vuelos a Lima (1h), Bogotá, Santiago. Lima-Madrid directo 12h.' },
      { icon: 'euro', titulo: 'Coste de vida 54% menor', desc: 'Lo que cuesta vivir en Madrid con 2.800€ se consigue en Cusco con 1.290€.' },
      { icon: 'shield', titulo: 'Seguridad de capital', desc: 'Cusco es una de las ciudades más seguras del país. Policía de turismo dedicada.' },
      { icon: 'heart', titulo: 'Comunidad española', desc: 'Más de 2.000 españoles residiendo. Red activa de expatriados y eventos mensuales.' },
    ],
    inversion: { precio_m2: 1820, retorno: 9.4, tendencia: 'creciente' },
  },
  lima: {
    nombre: 'Lima',
    tipo: 'costa',
    capital: 'Lima',
    altitud: '154 m',
    clima: '16 — 28°C',
    hero: 'https://images.unsplash.com/photo-1531065208531-4036c0dba3ca?w=1600&q=80',
    imagen_side: 'https://images.unsplash.com/photo-1580619305218-8423a7ef79b4?w=1200&q=80',
    tagline: 'Capital gastronómica del continente · Pacífico urbano',
    descripcion: 'Metrópoli de 10 millones frente al Pacífico. Miraflores y Barranco ofrecen vista al mar, vida cultural, mejores restaurantes del mundo y clima templado todo el año.',
    cultura: {
      patrimonio: ['Centro Histórico UNESCO', 'Huaca Pucllana', 'Museo Larco', 'MALI'],
      festivales: ['Señor de los Milagros · octubre', 'Festival gastronómico Mistura', 'Mes morado'],
      idiomas: ['Español'],
      artesania: ['Retablo ayacuchano', 'Mate burilado', 'Plata peruana'],
    },
    turismo: [
      { nombre: 'Barranco', tipo: 'Barrio bohemio', desc: 'Puente de los Suspiros, galerías, bares de pisco.', tiempo: 'En ciudad', img: 'https://images.unsplash.com/photo-1531968455001-5c5272a41129?w=800&q=80' },
      { nombre: 'Malecón de Miraflores', tipo: 'Urbano', desc: '10 km de parques sobre acantilados del Pacífico.', tiempo: 'En ciudad', img: 'https://images.unsplash.com/photo-1531065208531-4036c0dba3ca?w=800&q=80' },
      { nombre: 'Huaca Pucllana', tipo: 'Arqueológico', desc: 'Pirámide pre-inca de adobe en medio de la ciudad.', tiempo: '2h', img: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800&q=80' },
      { nombre: 'Islas Palomino', tipo: 'Natural', desc: 'Nadar con lobos marinos a 30 min de Callao.', tiempo: 'Medio día', img: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80' },
      { nombre: 'Paracas', tipo: 'Natural', desc: 'Reserva nacional, islas Ballestas "Galápagos peruano".', tiempo: '3h · fin de semana', img: 'https://images.unsplash.com/photo-1518709414768-a88981a4515d?w=800&q=80' },
      { nombre: 'Circuito Magic Water', tipo: 'Urbano', desc: 'Parque de fuentes iluminadas, récord Guinness.', tiempo: 'Noche', img: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&q=80' },
    ],
    gastronomia: [
      { nombre: 'Ceviche clásico', desc: 'Pescado del día, limón, ají limo, camote y choclo.', donde: 'La Mar, Pescados Capitales', img: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=700&q=80' },
      { nombre: 'Menú degustación Central', desc: '#1 World\'s 50 Best. Altitudes de Perú en 17 platos.', donde: 'Central · Barranco', img: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=700&q=80' },
      { nombre: 'Nikkei en Maido', desc: '#2 mundial. Fusión japonesa-peruana de Mitsuharu.', donde: 'Maido · Miraflores', img: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=700&q=80' },
      { nombre: 'Anticuchos', desc: 'Corazón de res marinado en ají panca, a la brasa.', donde: 'Grimanesa Vargas', img: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=700&q=80' },
      { nombre: 'Causa limeña', desc: 'Papa amarilla prensada con ají, pollo o atún.', donde: 'Isolina · Barranco', img: 'https://images.unsplash.com/photo-1604909053522-f6bae95b1c82?w=700&q=80' },
      { nombre: 'Pisco Sour', desc: 'El cóctel nacional. Pisco, limón, clara, amargo.', donde: 'Hotel Maury (original)', img: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=700&q=80' },
    ],
    beneficios: [
      { icon: 'sun', titulo: 'Clima templado todo el año', desc: 'Sin frío extremo ni calor sofocante. Entre 16° y 28°C. Nunca llueve realmente.' },
      { icon: 'med', titulo: 'Medicina de primer nivel', desc: 'Clínica Anglo Americana, Delgado, San Felipe. Cobertura Sanitas España.' },
      { icon: 'wifi', titulo: 'Fibra óptica 500Mb', desc: 'Infraestructura top del continente. Hubs tech en San Isidro y Miraflores.' },
      { icon: 'edu', titulo: 'Colegios europeos', desc: 'Colegio Alexander von Humboldt, Franco Peruano, San Silvestre. Universidad UPC.' },
      { icon: 'plane', titulo: 'Hub aéreo sudamericano', desc: 'Aeropuerto Jorge Chávez: vuelos directos a Madrid (12h), Ámsterdam, LA, Miami.' },
      { icon: 'euro', titulo: 'Coste de vida 42% menor', desc: 'Sueldo madrileño de 2.800€ rinde como 4.830€. Restaurantes Michelin a 1/3 del precio.' },
      { icon: 'shield', titulo: 'Distritos premium seguros', desc: 'Miraflores, San Isidro y Barranco con seguridad 24/7 y patrullaje municipal.' },
      { icon: 'heart', titulo: '30.000 españoles residentes', desc: 'Cámara de Comercio España-Perú, Instituto Cervantes, comunidad consolidada.' },
    ],
    inversion: { precio_m2: 2180, retorno: 7.2, tendencia: 'estable' },
  },
  arequipa: {
    nombre: 'Arequipa',
    tipo: 'sierra',
    capital: 'Arequipa',
    altitud: '2.335 m',
    clima: '8 — 23°C',
    hero: 'https://images.unsplash.com/photo-1543349689-9a4d426bee8e?w=1600&q=80',
    imagen_side: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=80',
    tagline: 'La Ciudad Blanca · Sillar volcánico y 300 días de sol',
    descripcion: 'Construida en sillar blanco al pie del volcán Misti. Centro UNESCO. Clima perfecto, cocina más elaborada del país, ritmo sereno y provinciano sin perder sofisticación.',
    cultura: {
      patrimonio: ['Centro Histórico UNESCO', 'Monasterio de Santa Catalina', 'Iglesia de la Compañía'],
      festivales: ['Aniversario de Arequipa · agosto', 'Semana Santa', 'Virgen de Chapi'],
      idiomas: ['Español', 'Quechua', 'Aimara'],
      artesania: ['Textiles de alpaca', 'Tallado en sillar', 'Cuero repujado'],
    },
    turismo: [
      { nombre: 'Cañón del Colca', tipo: 'Natural', desc: 'Segundo cañón más profundo del mundo. Cóndores al amanecer.', tiempo: '3h · 2 días', img: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800&q=80' },
      { nombre: 'Monasterio Santa Catalina', tipo: 'Histórico', desc: 'Ciudadela religiosa del siglo XVI, 20.000 m².', tiempo: '3h', img: 'https://images.unsplash.com/photo-1543349689-9a4d426bee8e?w=800&q=80' },
      { nombre: 'Volcán Misti', tipo: 'Aventura', desc: 'Ascenso de 5.822m, vistas del valle arequipeño.', tiempo: '2 días', img: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80' },
      { nombre: 'Valle de los Volcanes', tipo: 'Natural', desc: 'Andagua: 80 conos volcánicos en un valle verde.', tiempo: '5h · 3 días', img: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&q=80' },
      { nombre: 'Ruta del Sillar', tipo: 'Cultural', desc: 'Canteras donde se extrae la piedra blanca de Arequipa.', tiempo: 'Medio día', img: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80' },
      { nombre: 'Mundo Alpaca', tipo: 'Cultural', desc: 'Centro textil Michell, alpacas y telares vivos.', tiempo: '2h', img: 'https://images.unsplash.com/photo-1589182337358-2cb63099350c?w=800&q=80' },
    ],
    gastronomia: [
      { nombre: 'Rocoto relleno', desc: 'Rocoto rojo picante con carne, pasas, queso gratinado.', donde: 'La Nueva Palomino', img: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=700&q=80' },
      { nombre: 'Adobo arequipeño', desc: 'Cerdo en chicha de jora, domingo en picantería.', donde: 'Picantería La Cau Cau', img: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=700&q=80' },
      { nombre: 'Ocopa', desc: 'Papas con crema de huacatay, maní y ají mirasol.', donde: 'Zig Zag', img: 'https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=700&q=80' },
      { nombre: 'Chupe de camarones', desc: 'Sopa espesa de camarones de río, huevo, queso.', donde: 'Sol de Mayo', img: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=700&q=80' },
      { nombre: 'Queso helado', desc: 'Postre arequipeño: helado de leche con canela y coco.', donde: 'Plaza de Armas', img: 'https://images.unsplash.com/photo-1488900128323-21503983a07e?w=700&q=80' },
      { nombre: 'Pastel de papa', desc: 'Capas de papa, queso, anís, horneado.', donde: 'Picanterías', img: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=700&q=80' },
    ],
    beneficios: [
      { icon: 'sun', titulo: '300 días de sol al año', desc: 'Clima excepcional a 2.335m: sin humedad, cielos despejados, templado.' },
      { icon: 'med', titulo: 'Red de salud consolidada', desc: 'Clínica Arequipa, San Juan de Dios. Universidad Católica Santa María (medicina).' },
      { icon: 'wifi', titulo: 'Fibra 300Mb extendida', desc: 'Cobertura en todo Cayma, Yanahuara, Cerro Colorado.' },
      { icon: 'edu', titulo: 'Universidades centenarias', desc: 'Universidad Nacional San Agustín, Santa María. Colegios privados de excelencia.' },
      { icon: 'plane', titulo: 'Vuelos diarios a Lima', desc: 'Aeropuerto Rodríguez Ballón: 1h20 a Lima, conexión a Madrid.' },
      { icon: 'euro', titulo: 'Coste de vida 51% menor', desc: 'Alquiler centro 2hab desde 560€. Almuerzo típico 8€.' },
      { icon: 'shield', titulo: 'Ciudad tranquila', desc: 'Tamaño medio (1M hab), ritmo pausado, baja criminalidad en zonas premium.' },
      { icon: 'heart', titulo: 'Identidad cultural fuerte', desc: 'Ciudad orgullosa de su historia. Comunidad cálida y abierta al extranjero.' },
    ],
    inversion: { precio_m2: 1540, retorno: 7.8, tendencia: 'creciente' },
  },
};

window.REGION_DATA = REGION_DATA;
